LPD-15246 Substitution of previously failing Poshi test for a Playwright one
liferay-headless/liferay-portal pull request #1851
Opened 2024-02-01 15:15 UTC by jalber786

**What's new?:**
- Added new Playwright test in exchange of a previously failing test.
- Added new POM for API Explorer.

**What's changed?:**
- Deleted previously failing Poshi text.
- Started using the POM of API Explorer in the other Playwright tests.

See the following **Jira ticket**: [LPD-15246](https://liferay.atlassian.net/browse/LPD-15246)

**NOTE:** The first commit of this PR is https://github.com/liferay-headless/liferay-portal/commit/5628534c53fd1c85406e58f50910fe7d12b36876

2024-02-01 15:15 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-02-01 15:15 UTC, jalber786 commented
ci:test:relevant

2024-02-01 15:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/3552/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3552/jenkins-report.html">here</a>.</b></p>

2024-02-01 17:27 UTC, 4lejandrito requested changes
@jalber786 this has conflicts with latest master.

2024-02-02 07:56 UTC, jalber786 commented
ci:test:sf

2024-02-02 07:57 UTC, jalber786 commented
ci:test:relevant

2024-02-02 07:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/12667/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12667/jenkins-report.html">here</a>.</b></p>

2024-02-02 07:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-17.liferay.com/job/test-portal-source-format/6774/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6774/jenkins-report.html">here</a>.</b></p>

2024-02-02 08:04 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d301aea2246a87ce6cb26441782e8e5b4f71ee8f">d301aea2246a87ce6cb26441782e8e5b4f71ee8f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/jalber786/liferay-portal/tree/LPD-15246">LPD-15246</a><br/>Branch GIT ID: <a href="https://github.com/jalber786/liferay-portal/commit/f6479d1f28ffded1c02f5ded2b29f7f7cf3ced68">f6479d1f28ffded1c02f5ded2b29f7f7cf3ced68</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-17.liferay.com/job/test-portal-source-format/6774/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6774/jenkins-report.html">here</a>.</h5></details></html>

2024-02-02 08:04 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/12667/">test-portal-acceptance-pullrequest(master)#12667</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12667/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/1851">liferay-headless#1851</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2533889969">[master] ci:test:relevant - jalber786 &gt; liferay-headless - PR#1851 - 2024-02-01[23:57:18]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2533889969<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/29448/">publish-testray-report#29448</a><br/></div></div>

2024-02-02 08:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-17.liferay.com/job/test-portal-source-format/6774/">test-portal-source-format#6774</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6774/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/1851">liferay-headless#1851</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2533890298">[master] ci:test:sf - jalber786 &gt; liferay-headless - PR#1851 - 2024-02-01[23:57:08]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2533890298<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-17.liferay.com/job/publish-testray-report/3754/">publish-testray-report#3754</a><br/></div></div>

2024-02-02 08:22 UTC, 4lejandrito requested changes

2024-02-02 08:22 UTC, 4lejandrito commented on modules/test/playwright/tests/headless-builder-web/apiExplorer.spec.ts
> +	page.waitForLoadState();
@jalber786 this is an async call. It should be awaited. If the test passes like this, it is better to remove this line because it has no effect.

2024-02-02 08:22 UTC, 4lejandrito commented on modules/test/playwright/tests/headless-builder-web/apiExplorer.spec.ts
> +export const test = mergeTests(
The test fails with a clean DB with no FFs enabled. You need to enable the API Builder feature flag here.

2024-02-02 08:22 UTC, 4lejandrito commented on modules/test/playwright/pages/headless-discovery-web/apiExplorerPage.ts
> +	async endpointHasSpecificParameters(
Rename to `endpointHasParameters`. The `specific` word adds no meaning. Simpler is better.

2024-02-02 08:22 UTC, 4lejandrito commented on modules/test/playwright/pages/headless-discovery-web/apiExplorerPage.ts
> +	async endpointHasNotSpecificParameters(
Same here.

2024-02-02 08:22 UTC, 4lejandrito commented on modules/test/playwright/pages/headless-discovery-web/apiExplorerPage.ts
> +	async goToSpecificApplication(applicationURL: string) {
Same here.

2024-02-02 08:22 UTC, 4lejandrito commented on modules/test/playwright/tests/headless-builder-web/apiExplorer.spec.ts
> +test('can see filter and sort parameters for collection but not for singleElement endpoints', async ({
I think it would be better to split this in 2 tests, one for the single parameter and another for collection.

2024-02-02 08:58 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 0 out of 2 jobs passed in 52 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/343">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1367401_5041</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d301aea2246a87ce6cb26441782e8e5b4f71ee8f">d301aea2246a87ce6cb26441782e8e5b4f71ee8f</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5d0e1ce7d96f69a3ad72b47030e2ba76e4c821a8">5d0e1ce7d96f69a3ad72b47030e2ba76e4c821a8</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2533705169">EE Development Acceptance (master) - 341 - 2024-02-01[00:42:02]</a></p><details><summary><strong>ci:test:playwright - 0 out of 2 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/5041/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/790628/"><strike>playwright-js-tomcat90-mysql57-jdk8/0/0</strike></a></li></ul></li></ul></div></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5041/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/790628//consoleText">playwright-js-tomcat90-mysql57-jdk8/0/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-02/test-1-36/test-portal-acceptance-pullrequest(master)/5041/playwright-js-tomcat90-mysql57-jdk8/0/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/790628/testReport/headless-builder-web/apiExplorer.spec/ts">headless-builder-web/apiExplorer.spec.ts</a></summary><div><ol><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/790628//testReport/headless-builder-web/apiExplorer.spec/ts/can_see_filter_and_sort_parameters_for_collection_but_not_for_singleElement_endpoints">can see filter and sort parameters for collection but not for singleElement endpoints</a></li></ol></div></details></li><li><details><summary><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/790628/testReport/object-web/modelBuilder.spec/ts">object-web/modelBuilder.spec.ts</a></summary><div><ol><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/790628//testReport/object-web/modelBuilder.spec/ts/can_create_relationship_by_dragging_node_handles">can create relationship by dragging node handles</a></li></ol></div></details></li><li><details><summary><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/790628/testReport/object-web/objectFolder.spec/ts">object-web/objectFolder.spec.ts</a></summary><div><ol><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/790628//testReport/object-web/objectFolder.spec/ts/created_object_folders_are_on_the_left_side_bar">created object folders are on the left side bar</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/790628//testReport/object-web/objectFolder.spec/ts/default_folder_does_not_contains_delete_and_edit_options">default folder does not contains delete and edit options</a></li></ol></div></details></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-36/jobs/test-portal-acceptance-pullrequest(master)/builds/5041/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-36/jobs/test-portal-acceptance-pullrequest(master)/builds/5041/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-36/jobs/test-portal-acceptance-pullrequest(master)/builds/5041/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2024-02-02 09:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/5041/">test-portal-acceptance-pullrequest(master)#5041</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5041/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/1851">liferay-headless#1851</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2533915294">[master] ci:test:playwright - jalber786 &gt; liferay-headless - PR#1851 - 2024-02-02[00:05:27]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2533915294<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/10873/">publish-testray-report#10873</a><br/></div></div>

2024-02-02 09:05 UTC, jalber786 commented
ci:test:sf

2024-02-02 09:05 UTC, jalber786 commented
ci:test:playwright

2024-02-02 09:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/9283/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9283/jenkins-report.html">here</a>.</b></p>

2024-02-02 09:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/5322/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/5322/jenkins-report.html">here</a>.</b></p>

2024-02-02 09:12 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/98adf062e8deb8f7c598eb548f09b5fdb2cfb120">98adf062e8deb8f7c598eb548f09b5fdb2cfb120</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/jalber786/liferay-portal/tree/LPD-15246">LPD-15246</a><br/>Branch GIT ID: <a href="https://github.com/jalber786/liferay-portal/commit/62b680c9a54e1d16f03a44a6f01dfd7eb162d8ab">62b680c9a54e1d16f03a44a6f01dfd7eb162d8ab</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/5322/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/5322/jenkins-report.html">here</a>.</h5></details></html>

2024-02-02 09:15 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/5322/">test-portal-source-format#5322</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/5322/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/1851">liferay-headless#1851</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2533919063">[master] ci:test:sf - jalber786 &gt; liferay-headless - PR#1851 - 2024-02-02[01:05:55]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2533919063<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/19552/">publish-testray-report#19552</a><br/></div></div>

2024-02-02 09:36 UTC, 4lejandrito approved these changes
See my commits.

2024-02-02 10:03 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 8 out of 11 jobs passed in 57 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/98adf062e8deb8f7c598eb548f09b5fdb2cfb120">98adf062e8deb8f7c598eb548f09b5fdb2cfb120</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5d0e1ce7d96f69a3ad72b47030e2ba76e4c821a8">5d0e1ce7d96f69a3ad72b47030e2ba76e4c821a8</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2533705169">EE Development Acceptance (master) - 341 - 2024-02-01[00:42:02]</a></p><details><summary><strong>ci:test:playwright - 8 out of 11 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/9283/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/547162/">playwright-js-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389885/">playwright-js-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1020552/">playwright-js-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/363976/">playwright-js-tomcat90-mysql57-jdk8/3/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/331544/">playwright-js-tomcat90-mysql57-jdk8/4/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/319394/">playwright-js-tomcat90-mysql57-jdk8/5/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/356748/">playwright-js-tomcat90-mysql57-jdk8/6/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347536/"><strike>playwright-js-tomcat90-mysql57-jdk8/7/0</strike></a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/355361/">playwright-js-tomcat90-mysql57-jdk8/8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/331543/"><strike>playwright-js-tomcat90-mysql57-jdk8/9/0</strike></a></li></ul></li></ul></div><details><summary><strong>8 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9283/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347536//consoleText">playwright-js-tomcat90-mysql57-jdk8/7/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-02/test-1-39/test-portal-acceptance-pullrequest(master)/9283/playwright-js-tomcat90-mysql57-jdk8/7/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347536/testReport/object-web/modelBuilder.spec/ts">object-web/modelBuilder.spec.ts</a></summary><div><ol><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347536//testReport/object-web/modelBuilder.spec/ts/can_create_relationship_by_dragging_node_handles">can create relationship by dragging node handles</a></li></ol></div></details></li><li><details><summary><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347536/testReport/object-web/objectFolder.spec/ts">object-web/objectFolder.spec.ts</a></summary><div><ol><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347536//testReport/object-web/objectFolder.spec/ts/created_object_folders_are_on_the_left_side_bar">created object folders are on the left side bar</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347536//testReport/object-web/objectFolder.spec/ts/default_folder_does_not_contains_delete_and_edit_options">default folder does not contains delete and edit options</a></li></ol></div></details></li></ol></div></li><li><div><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/331543//consoleText">playwright-js-tomcat90-mysql57-jdk8/9/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-02/test-1-39/test-portal-acceptance-pullrequest(master)/9283/playwright-js-tomcat90-mysql57-jdk8/9/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/331543/testReport/object-web/modelBuilder.spec/ts">object-web/modelBuilder.spec.ts</a></summary><div><ol><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/331543//testReport/object-web/modelBuilder.spec/ts/can_create_relationship_by_dragging_node_handles">can create relationship by dragging node handles</a></li></ol></div></details></li><li><details><summary><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/331543/testReport/object-web/objectFolder.spec/ts">object-web/objectFolder.spec.ts</a></summary><div><ol><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/331543//testReport/object-web/objectFolder.spec/ts/created_object_folders_are_on_the_left_side_bar">created object folders are on the left side bar</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/331543//testReport/object-web/objectFolder.spec/ts/default_folder_does_not_contains_delete_and_edit_options">default folder does not contains delete and edit options</a></li></ol></div></details></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-39/jobs/test-portal-acceptance-pullrequest(master)/builds/9283/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-39/jobs/test-portal-acceptance-pullrequest(master)/builds/9283/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-39/jobs/test-portal-acceptance-pullrequest(master)/builds/9283/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2024-02-02 10:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/9283/">test-portal-acceptance-pullrequest(master)#9283</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9283/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/1851">liferay-headless#1851</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2533926990">[master] ci:test:playwright - jalber786 &gt; liferay-headless - PR#1851 - 2024-02-02[01:06:03]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2533926990<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/19553/">publish-testray-report#19553</a><br/></div></div>

2024-02-02 10:09 UTC, 4lejandrito commented
ci:forward

2024-02-02 10:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-source-format/5806/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/5806/jenkins-report.html">here</a>.</b></p>

2024-02-02 10:19 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 9 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/98adf062e8deb8f7c598eb548f09b5fdb2cfb120">98adf062e8deb8f7c598eb548f09b5fdb2cfb120</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/jalber786/liferay-portal/tree/LPD-15246">LPD-15246</a><br/>Branch GIT ID: <a href="https://github.com/jalber786/liferay-portal/commit/fb42928757be2cb02bf60f283f5515e45317947b">fb42928757be2cb02bf60f283f5515e45317947b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-source-format/5806/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/5806/jenkins-report.html">here</a>.</h5></details></html>

2024-02-02 10:20 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-7.liferay.com/job/test-portal-source-format/5806//consoleFull)

2024-02-02 10:20 UTC, closed without merging

2024-02-02 10:20 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/146878
[Console](https://test-1-7.liferay.com/job/test-portal-source-format/5806//consoleFull)

2024-02-02 10:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-7.liferay.com/job/test-portal-source-format/5806/">test-portal-source-format#5806</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/5806/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/1851">liferay-headless#1851</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2533929123">[master] ci:test:sf - jalber786 &gt; liferay-headless - PR#1851 - 2024-02-02[02:10:42]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2533929123<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-7.liferay.com/job/publish-testray-report/3628/">publish-testray-report#3628</a><br/></div></div>

2024-02-02 11:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/4744/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4744/jenkins-report.html">here</a>.</b></p>

2024-02-02 12:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/4744/">test-portal-acceptance-pullrequest(master)#4744</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4744/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/1851">liferay-headless#1851</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2533996666">[master] ci:test:relevant - jalber786 &gt; liferay-headless - PR#1851 - 2024-02-02[03:53:13]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2533996666<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/9804/">publish-testray-report#9804</a><br/></div></div>