LPD-36535 recognize nested field as a valid value
liferay-headless/liferay-portal pull request #2265
Opened 2024-10-11 12:11 UTC by ZakiMiklos

https://liferay.atlassian.net/browse/LPD-36535

2024-10-11 12:11 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-10-11 12:13 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/10325/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10325/jenkins-report.html">here</a>.</b></p>

2024-10-11 12:15 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/053f48c2e1af9e8c2d1962b3f6fcf6dd10dda019">053f48c2e1af9e8c2d1962b3f6fcf6dd10dda019</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ZakiMiklos/liferay-portal/tree/LPD-36535-2">LPD-36535-2</a><br/>Branch GIT ID: <a href="https://github.com/ZakiMiklos/liferay-portal/commit/89eafe45a4216df435a84e0990a6d4d09ec6b884">89eafe45a4216df435a84e0990a6d4d09ec6b884</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/10325/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10325/jenkins-report.html">here</a>.</h5></details></html>

2024-10-11 12:15 UTC, ZakiMiklos commented
ci:relevant

2024-10-11 12:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/10325/">test-portal-source-format#10325</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10325/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/2265">liferay-headless#2265</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/38928472">[master] ci:test:sf - ZakiMiklos &gt; liferay-headless - PR#2265 - 2024-10-11[05:11:44]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>38928472<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/39411/">publish-testray-report#39411</a><br/></div></div>

2024-10-14 09:22 UTC, albertojml commented on modules/apps/object/object-service/src/main/java/com/liferay/object/internal/field/business/type/RelationshipObjectFieldBusinessType.java
I think this is not the correct way to fix the issue. 

The validation fails as I said before in the `DefaultObjectEntryManagerImpl.addObjectEntry` as it tries validating that mandatory fields through the `_objectEntryService.addObjectEntry(` statement found in the line 156. This issue is still happening (see the attached screenshot) 
![image](https://github.com/user-attachments/assets/8d9cdfa0-1c91-42c8-a74e-bfa5ddce0f4c)

Also, this PR doesn't fix the issue of the validation order. As stated by the LPD-36173 story description "...when the API request is sent, the creation of the object prioritizes the relationship fields in a specific order... should be nested Field -> Id -> ERC..." (the priority with the PR is nestedField -> ERC -> Id)

Please rework it.

2024-10-14 09:22 UTC, albertojml requested changes
Please take a look at my comments

2024-10-16 08:43 UTC, closed without merging