Product QA | Automation Test Creation - LPS-153326 - Allow developers to make a relationship with a system object through API
liferay-headless/liferay-portal pull request #872
Opened 2022-11-18 09:23 UTC by Hijky

**Background**
Add a testcase to make a relationship with a system object through API

**Test Plan**
Given a foundation object
Given manyToMany relationship usersFoundations created
Given two foundation entries created
Given two userAccount entries created
When each foundation is related to each userAccount through userAccounts PUT endpoint
Then I can see the entry correctly related in GET request response

Given a foundation object
Given manyToMany relationship usersFoundations created
Given two foundation entries created
Given two userAccount entries created
Given each foundation is related to each userAccount through userAccounts PUT endpoint
When deleting one of the foundation entries
Then I can see only one entry correctly related in GET request response

Given a foundation object
Given manyToMany relationship usersFoundations created
Given two foundation entries created
Given two userAccount entries created
Given each foundation related to each userAccount through userAccounts PUT endpoint
When deleting all of the foundation entries
Then I can see no one entry correctly related in GET request response

Given a foundation object
Given oneToMany relationship usersFoundations created
Given two foundation entries created
Given the userAccount entry created
Given I relate all the foundation entries with the userAccount entry through the userAccount PUT endpoint
When deleting one of the foundation entries
Then I can see only one entry correctly related in GET request response

Given a firstFoundation object
Given oneToMany relationship usersFirstFoundations created
Given a secondFoundation object
Given manyToMany relationship usersSecondFoundations created
Given two foundation entries created
Given the userAccount entry created
When I relate each foundation entry with the userAccount entry through the userAccount PUT endpoint with different relationships
Then I can see the two entries correctly related in GET request response

**JIRA Link:**
https://issues.liferay.com/browse/LPS-153326

2022-11-18 09:23 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-11-18 09:24 UTC, Hijky commented
ci:test:sf

2022-11-18 09:24 UTC, Hijky commented
ci:test:relevant

2022-11-18 09:25 UTC, Hijky commented
ci:test:headless-frontend-functional:nocompile

2022-11-18 09:25 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-11-18 09:25 UTC, liferay-continuous-integration commented
The test suite specified is not a valid test suite.
Please refer to the available test suites below.
#### ci:test[:suite][:SHA|nocompile|norebase|gist-SHA]
&nbsp;&nbsp;&nbsp;&nbsp;Test the pull request. Optionally specify the name of the test suite and/or optionally specify the upstream SHA to test against or use "nocompile" to test with a prebuilt bundle or use "norebase" to test without rebasing.
<details><summary><strong>Available test suites:</strong></summary>

- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance** - Test acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-functional** - Test acceptance functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-functional-db-partition** - Test acceptance functional tests with Database Partitioning.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-release** - Compile a release bundle and execute acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-upstream** - Test acceptance upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**account** - Test Account tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud** - Test Analytics Cloud tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud-acceptance** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud-quarantine** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**app-servers** - Test Deployments on App Servers.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**auto-tagging** - Test Auto Tagging tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**backend** - Test backend tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**backend-hypersonic** - Test backend tests on Hypersonic.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**blade** - Test Blade samples tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**blogs** - Test Blogs tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**bulk-editing** - Test Bulk Editing tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**bundle** - Saves a compiled tomcat bundle.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**calendar** - Test Calendar tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**click-to-chat** - Test Click to Chat tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**clustering** - Test clustering tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**comment** - Test Comment tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce** - Test only Commerce tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-database** - Test only Commerce Database tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-es7-remote** - Test only Commerce tests with the latest compatible remote Elasticsearch 7 version.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-functional** - Test only Commerce functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**content-page-review** - Test Content Page Review (comments) tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**continuous-integration** - Test Continuous Integration tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**cookies** - Test Cookie Preferences tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-engine** - Test Data Engine functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-integration** - Test only Data Integration tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-integration-functional** - Test only functional Data Integration tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**db-partition** - Test Database Partitioning functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**depot** - Test Depot tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**digital-signature** - Test Digital Signature tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**dl-store** - Test Document Library Store tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**document** - Test Document and Media tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**drools** - Test Drools tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**dummy** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo** - Test all Echo (WCM) team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-acceptance** - Test Echo (WCM) team acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-db-partition** - Test Echo (WCM) team acceptance tests with Database Partitioning.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-upgrade** - Test Echo (WCM) team upgrade tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**environments** - Test environment acceptance functional tests on all available environment stacks.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**export-import** - Test exportimport tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**forms** - Test forms tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**forms-functional** - Test only functional forms tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**friendly-url** - Test Friendly URL tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend** - Test all Frontend Infra team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-clay** - Test Frontend Infra team Clay tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-data-set** - Test frontend data set tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-dev-exp** - Test frontend developer experience tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-remote-apps** - Test frontend remote apps tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-ui** - Test frontend ui tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-walkthrough** - Test frontend walkthrough tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gauntlet** - Test upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gauntlet-bucket** - Test a subset of upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gradle-plugins** - Test Gradle Plugins tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless** - Test all headless team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless-acceptance** - Test headless team acceptance tests considering Headless and Rest Builder.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless-functional** - Headless Team functional API tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**item-selector** - Test item selector tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**jdk11** - Test acceptance, smoke, and upgrade functional tests against JDK11.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**jsf** - Test Liferay Faces tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**kaleo-forms** - Test Kaleo Forms admin tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**knowledge-base** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**ldap** - Test LDAP tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**license** - Compile a release bundle and execute tests for licensing.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**license-cluster** - Compile a release bundle and execute tests for cluster licensing on 32GB slaves.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**liferay-online** - Compile a release bundle and execute tests with liferay online properties.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**lima** - Test Lima tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**lima-acceptance** - Test Lima acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**lima-db-partition** - Test Lima functional tests with Database Partitioning.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**lima-upgrade** - Test Lima upgrade tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**lpkg** - Test LPKG tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**message-boards** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**mfa** - Test Multi Factor Authentication tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**notifications** - Test Notifications tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**oauth2** - Test OAuth 2 tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**object** - Test Object tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**oidc** - Test OpenID Connect tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**onedrive** - Test OneDrive tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**online-editing** - Test Online Editing tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**osb-site-initializer-customer-portal** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**osb-site-initializer-partner-portal** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**password-policies** - Test Password Policies tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**portlet-deploym [...]

2022-11-18 09:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/1202/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1202/jenkins-report.html">here</a>.</b></p>

2022-11-18 09:26 UTC, Hijky commented
ci:test:headless-functional:nocompile

2022-11-18 09:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/6421/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6421/jenkins-report.html">here</a>.</b></p>

2022-11-18 09:26 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-11-18 09:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>headless-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/4904/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4904/jenkins-report.html">here</a>.</b></p>

2022-11-18 09:28 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/67b4cf6bb65b6734267cac21dcc2a242a094f033">67b4cf6bb65b6734267cac21dcc2a242a094f033</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hijky/liferay-portal/tree/master-LPS-153326">master-LPS-153326</a><br/>Branch GIT ID: <a href="https://github.com/Hijky/liferay-portal/commit/44f415561917b53cd5d032a47107374a6c3384ce">44f415561917b53cd5d032a47107374a6c3384ce</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/1202/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1202/jenkins-report.html">here</a>.</h5></details></html>

2022-11-18 09:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/1202/">test-portal-source-format#1202</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1202/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2062375515">[master] ci:test:sf - Hijky &gt; liferay-headless - PR#872 - 2022-11-18[01:24:50]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/3932/">publish-testray-report#3932</a><br/></div></div>

2022-11-18 09:32 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/6421/">test-portal-acceptance-pullrequest(master)#6421</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6421/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2062375544">[master] ci:test:relevant - Hijky &gt; liferay-headless - PR#872 - 2022-11-18[01:25:58]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/14951/">publish-testray-report#14951</a><br/></div></div>

2022-11-18 10:32 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:headless-functional - 12 out of 17 jobs passed in 1 hour 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/67b4cf6bb65b6734267cac21dcc2a242a094f033">67b4cf6bb65b6734267cac21dcc2a242a094f033</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/67b4cf6bb65b6734267cac21dcc2a242a094f033">67b4cf6bb65b6734267cac21dcc2a242a094f033</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2062447285">EE Development Acceptance (master) - 4036 - 2022-11-17[22:36:06]</a></p><details><summary><strong>ci:test:headless-functional - 12 out of 17 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/4904/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/130895/"><strike>functional-tomcat90-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/132540/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/308629/"><strike>functional-tomcat90-mysql57-jdk8/0/2</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/259559/"><strike>functional-tomcat90-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/333441/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/307770/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/111927/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/131886/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/328454/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/308630/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/132541/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/117887/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/129747/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/110304/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/283232/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/278420/">functional-tomcat90-mysql57-jdk8/0/15</a></li></ul></li></ul></div><details><summary><strong>12 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4904/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/130895//consoleText">functional-tomcat90-mysql57-jdk8/0/0</a><ol><li><div><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/130895//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ExtendPropertiesForSystemObjects_CanUpdateValueOfPropertyAddedToSystemObjectWithPatchRequest_">LocalFile.ExtendPropertiesForSystemObjects#CanUpdateValueOfPropertyAddedToSystemObjectWithPatchRequest</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/4904/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.ExtendPropertiesForSystemObjects_CanUpdateValueOfPropertyAddedToSystemObjectWithPatchRequest/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/4904/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.ExtendPropertiesForSystemObjects_CanUpdateValueOfPropertyAddedToSystemObjectWithPatchRequest/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/4904/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/2057753322/history">Failed 0 of last 16</a></div></li></ol></div></li><li><div><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/132540//consoleText">functional-tomcat90-mysql57-jdk8/0/1</a><ol><li><div><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/132540//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntries_">LocalFile.MakeARelationshipWithSystemObjectThroughAPI#CanRelateCustomObjectEntriesToSystemObjectEntries</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/4904/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntries/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/4904/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntries/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/4904/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/308629//consoleText">functional-tomcat90-mysql57-jdk8/0/2</a><ol><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/308629//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ExtendPropertiesForSystemObjects_CanUpdateValueOfPropertyAddedToSystemObjectWithPutRequest_">LocalFile.ExtendPropertiesForSystemObjects#CanUpdateValueOfPropertyAddedToSystemObjectWithPutRequest</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/4904/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.ExtendPropertiesForSystemObjects_CanUpdateValueOfPropertyAddedToSystemObjectWithPutRequest/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/4904/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.ExtendPropertiesForSystemObjects_CanUpdateValueOfPropertyAddedToSystemO [...]

2022-11-18 10:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/4904/">test-portal-acceptance-pullrequest(master)#4904</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4904/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>headless-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2062585132">[master] ci:test:headless-functional - Hijky &gt; liferay-headless - PR#872 - 2022-11-18[01:27:14]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/10990/">publish-testray-report#10990</a><br/></div></div>

2022-11-18 14:02 UTC, magjed4289 reviewed
There are errors in the tests, maybe there's a feature flag missing?

2022-11-21 01:37 UTC, Hijky commented
Sure, thanks Meg, I forgot to add the feature flag, I will add it.

2022-11-21 02:09 UTC, Hijky commented
ci:test:relevant

2022-11-21 02:09 UTC, Hijky commented
ci:test:headless-functional:nocompile

2022-11-21 02:09 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-11-21 02:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/5451/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5451/jenkins-report.html">here</a>.</b></p>

2022-11-21 02:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>headless-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/5892/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5892/jenkins-report.html">here</a>.</b></p>

2022-11-21 02:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/1222/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1222/jenkins-report.html">here</a>.</b></p>

2022-11-21 02:12 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c6c25dd4d9196cf16463271da12d6d1474b23808">c6c25dd4d9196cf16463271da12d6d1474b23808</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hijky/liferay-portal/tree/master-LPS-153326">master-LPS-153326</a><br/>Branch GIT ID: <a href="https://github.com/Hijky/liferay-portal/commit/aa4ffc897506f9c878a1ad5b75e2d061793acd97">aa4ffc897506f9c878a1ad5b75e2d061793acd97</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/1222/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1222/jenkins-report.html">here</a>.</h5></details></html>

2022-11-21 02:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/1222/">test-portal-source-format#1222</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1222/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2066682003">[master] ci:test:sf - Hijky &gt; liferay-headless - PR#872 - 2022-11-20[18:09:12]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/4031/">publish-testray-report#4031</a><br/></div></div>

2022-11-21 02:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/5451/">test-portal-acceptance-pullrequest(master)#5451</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5451/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2066682042">[master] ci:test:relevant - Hijky &gt; liferay-headless - PR#872 - 2022-11-20[18:09:25]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/13477/">publish-testray-report#13477</a><br/></div></div>

2022-11-21 02:48 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:headless-functional - 11 out of 18 jobs passed in 38 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c6c25dd4d9196cf16463271da12d6d1474b23808">c6c25dd4d9196cf16463271da12d6d1474b23808</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c6c25dd4d9196cf16463271da12d6d1474b23808">c6c25dd4d9196cf16463271da12d6d1474b23808</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2065994263">EE Development Acceptance (master) - 4043 - 2022-11-19[07:35:18]</a></p><details><summary><strong>ci:test:headless-functional - 11 out of 18 jobs PASSED</strong></summary><div><h4>7 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/5892/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/114380/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347827/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/114379/"><strike>functional-tomcat90-mysql57-jdk8/0/2</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347829/"><strike>functional-tomcat90-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/305740/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/114381/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347828/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/305741/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316716/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/114382/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/329888/"><strike>functional-tomcat90-mysql57-jdk8/0/10</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/324805/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347830/"><strike>functional-tomcat90-mysql57-jdk8/0/12</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/114383/"><strike>functional-tomcat90-mysql57-jdk8/0/13</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316715/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/305742/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347826/">functional-tomcat90-mysql57-jdk8/0/16</a></li></ul></li></ul></div><details><summary><strong>11 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5892/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at c6c25dd4d9196cf16463271da12d6d1474b23808:</strong></summary><ol><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347827//consoleText">functional-tomcat90-mysql57-jdk8/0/1</a><ol><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347827//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_HeadlessDeliveryBatchMode_CanCreateBlogPostingWithBatchPostCreateStrategyUpsert_">LocalFile.HeadlessDeliveryBatchMode#CanCreateBlogPostingWithBatchPostCreateStrategyUpsert</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5892/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.HeadlessDeliveryBatchMode_CanCreateBlogPostingWithBatchPostCreateStrategyUpsert/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5892/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.HeadlessDeliveryBatchMode_CanCreateBlogPostingWithBatchPostCreateStrategyUpsert/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5892/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/2066002662/history">Failed 4 of last 21</a></div></li><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347827//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_HeadlessDeliveryBatchMode_CanUpdateBlogPostingWithBatchPostCreateStrategyUpsertWhenOneOfThemAlreadyExisting_">LocalFile.HeadlessDeliveryBatchMode#CanUpdateBlogPostingWithBatchPostCreateStrategyUpsertWhenOneOfThemAlreadyExisting</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5892/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.HeadlessDeliveryBatchMode_CanUpdateBlogPostingWithBatchPostCreateStrategyUpsertWhenOneOfThemAlreadyExisting/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5892/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.HeadlessDeliveryBatchMode_CanUpdateBlogPostingWithBatchPostCreateStrategyUpsertWhenOneOfThemAlreadyExisting/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5892/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/2066003953/history">Failed 4 of last 21</a></div></li><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347827//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_HeadlessDeliveryBatchMode_CannotCreateBlogPostingWithBatchPutPartialUpdate_">LocalFile.HeadlessDeliveryBatchMode#CannotCreateBlogPostingWithBatchPutPartialUpdate</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5892/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.HeadlessDeliveryBatchMode_CannotCreateBlogPostingWithBatchPutPartialUpdate/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(ma [...]

2022-11-21 02:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/5892/">test-portal-acceptance-pullrequest(master)#5892</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5892/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>headless-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2066682311">[master] ci:test:headless-functional - Hijky &gt; liferay-headless - PR#872 - 2022-11-20[18:09:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/14130/">publish-testray-report#14130</a><br/></div></div>

2022-11-21 10:13 UTC, magjed4289 requested changes

2022-11-21 10:13 UTC, magjed4289 commented on portal-web/test/functional/com/liferay/portalweb/macros/headless/headlessadminuser/MakeARelationshipWithSystemObjectThroughAPI.testcase
> +		task ("Given a firstFoundation object") {
why don't we use the foundation object here as well? this way we could move all the foundation creation to the setup and we would start this test with creating secondFoundation

2022-11-22 04:03 UTC, Hijky commented
ci:test:sf

2022-11-22 04:03 UTC, Hijky commented
ci:test:relevant

2022-11-22 04:03 UTC, Hijky commented
ci:test:headless-functional:nocompile

2022-11-22 04:03 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-11-22 04:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/5904/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5904/jenkins-report.html">here</a>.</b></p>

2022-11-22 04:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/1235/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1235/jenkins-report.html">here</a>.</b></p>

2022-11-22 04:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>headless-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/5905/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5905/jenkins-report.html">here</a>.</b></p>

2022-11-22 04:13 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c1e7129f0993aa30e3f345ebd66fd58bc005e8e5">c1e7129f0993aa30e3f345ebd66fd58bc005e8e5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hijky/liferay-portal/tree/master-LPS-153326">master-LPS-153326</a><br/>Branch GIT ID: <a href="https://github.com/Hijky/liferay-portal/commit/1acb82590a89c2673b00bb70fdf9c29d44a5adfa">1acb82590a89c2673b00bb70fdf9c29d44a5adfa</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/1235/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1235/jenkins-report.html">here</a>.</h5></details></html>

2022-11-22 04:15 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/1235/">test-portal-source-format#1235</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1235/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2069620199">[master] ci:test:sf - Hijky &gt; liferay-headless - PR#872 - 2022-11-21[20:10:13]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/4096/">publish-testray-report#4096</a><br/></div></div>

2022-11-22 04:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/5904/">test-portal-acceptance-pullrequest(master)#5904</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5904/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2069620208">[master] ci:test:relevant - Hijky &gt; liferay-headless - PR#872 - 2022-11-21[20:10:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/14170/">publish-testray-report#14170</a><br/></div></div>

2022-11-22 04:57 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:headless-functional - 10 out of 18 jobs passed in 45 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c1e7129f0993aa30e3f345ebd66fd58bc005e8e5">c1e7129f0993aa30e3f345ebd66fd58bc005e8e5</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c1e7129f0993aa30e3f345ebd66fd58bc005e8e5">c1e7129f0993aa30e3f345ebd66fd58bc005e8e5</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2068009625">EE Development Acceptance (master) - 4044 - 2022-11-21[05:09:24]</a></p><details><summary><strong>ci:test:headless-functional - 10 out of 18 jobs PASSED</strong></summary><div><h4>8 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/5905/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/308210/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/308209/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/308208/"><strike>functional-tomcat90-mysql57-jdk8/0/2</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/337075/"><strike>functional-tomcat90-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/308212/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/337074/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/308211/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350432/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/308213/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/327158/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/319288/"><strike>functional-tomcat90-mysql57-jdk8/0/10</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/337076/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/327159/"><strike>functional-tomcat90-mysql57-jdk8/0/12</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/308214/"><strike>functional-tomcat90-mysql57-jdk8/0/13</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350433/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/319289/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/308207/"><strike>functional-tomcat90-mysql57-jdk8/0/16</strike></a></li></ul></li></ul></div><details><summary><strong>10 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5905/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/308207//consoleText">functional-tomcat90-mysql57-jdk8/0/16</a><ol><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/308207//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeARelationshipWithSystemObjectThroughAPI_CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany_">LocalFile.MakeARelationshipWithSystemObjectThroughAPI#CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5905/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5905/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5905/functional-tomcat90-mysql57-jdk8/0/16/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/308207//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany_">LocalFile.MakeARelationshipWithSystemObjectThroughAPI#CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5905/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5905/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5905/functional-tomcat90-mysql57-jdk8/0/16/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/308207//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntries_">LocalFile.MakeARelationshipWithSystemObjectThroughAPI#CanRelateCustomObjectEntriesToSystemObjectEntries</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5905/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntries/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5905/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntries/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullre [...]

2022-11-22 06:40 UTC, Hijky commented
ci:test:sf

2022-11-22 06:41 UTC, Hijky commented
ci:test:relevant

2022-11-22 06:41 UTC, Hijky commented
ci:test:headless-functional:nocompile

2022-11-22 06:41 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-11-22 06:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/4936/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4936/jenkins-report.html">here</a>.</b></p>

2022-11-22 06:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/3205/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/3205/jenkins-report.html">here</a>.</b></p>

2022-11-22 06:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>headless-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/6468/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6468/jenkins-report.html">here</a>.</b></p>

2022-11-22 06:44 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c1e7129f0993aa30e3f345ebd66fd58bc005e8e5">c1e7129f0993aa30e3f345ebd66fd58bc005e8e5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hijky/liferay-portal/tree/master-LPS-153326">master-LPS-153326</a><br/>Branch GIT ID: <a href="https://github.com/Hijky/liferay-portal/commit/4433c1b4d829b7ba38f8d73a93f346bcea58e919">4433c1b4d829b7ba38f8d73a93f346bcea58e919</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/3205/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/3205/jenkins-report.html">here</a>.</h5></details></html>

2022-11-22 06:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/4936/">test-portal-acceptance-pullrequest(master)#4936</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4936/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2069728008">[master] ci:test:relevant - Hijky &gt; liferay-headless - PR#872 - 2022-11-21[22:41:12]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/11057/">publish-testray-report#11057</a><br/></div></div>

2022-11-22 07:00 UTC, magjed4289 commented on portal-web/test/functional/com/liferay/portalweb/macros/headless/headlessadminuser/MakeARelationshipWithSystemObjectThroughAPI.testcase
> +		task ("Given manyToMany relationship usersFoundations created") {
there are still a lot of Given steps that can be moved all together to the setUp.

2022-11-22 08:00 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:headless-functional - 10 out of 18 jobs passed in 1 hour 17 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c1e7129f0993aa30e3f345ebd66fd58bc005e8e5">c1e7129f0993aa30e3f345ebd66fd58bc005e8e5</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c1e7129f0993aa30e3f345ebd66fd58bc005e8e5">c1e7129f0993aa30e3f345ebd66fd58bc005e8e5</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2068009625">EE Development Acceptance (master) - 4044 - 2022-11-21[05:09:24]</a></p><details><summary><strong>ci:test:headless-functional - 10 out of 18 jobs PASSED</strong></summary><div><h4>8 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/6468/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/286011/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/337200/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/130156/"><strike>functional-tomcat90-mysql57-jdk8/0/2</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/327268/"><strike>functional-tomcat90-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332455/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/132252/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/111623/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/131007/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/115649/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/100621/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/130342/"><strike>functional-tomcat90-mysql57-jdk8/0/10</strike></a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/119180/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/126138/"><strike>functional-tomcat90-mysql57-jdk8/0/12</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/286611/"><strike>functional-tomcat90-mysql57-jdk8/0/13</strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/120420/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/281772/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/133760/"><strike>functional-tomcat90-mysql57-jdk8/0/16</strike></a></li></ul></li></ul></div><details><summary><strong>10 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6468/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/133760//consoleText">functional-tomcat90-mysql57-jdk8/0/16</a><ol><li><div><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/133760//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany_">LocalFile.MakeARelationshipWithSystemObjectThroughAPI#CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6468/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6468/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6468/functional-tomcat90-mysql57-jdk8/0/16/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/133760//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntries_">LocalFile.MakeARelationshipWithSystemObjectThroughAPI#CanRelateCustomObjectEntriesToSystemObjectEntries</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6468/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntries/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6468/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntries/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6468/functional-tomcat90-mysql57-jdk8/0/16/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol><hr/><details><summary><strong>Failures in common with <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at c1e7129f0993aa30e3f345ebd66fd58bc005e8e5:</strong></summary><ol><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/337200//consoleText">functional-tomcat90-mysql57-jdk8/0/1</a><ol><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/337200//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_HeadlessDeliveryBatchMode_CanCreateBlogPostingWithBatchPostCreateStrategyUpsert_">LocalFile.HeadlessDeliveryBatchMode#CanCreateBlogPostingWithBatchPostCreateStrategyUpsert</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6468/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.HeadlessDeliveryBatchMode_CanCreateBlogPostingWithBatchPostCreateStrategyUpsert/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2 [...]

2022-11-22 08:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/6468/">test-portal-acceptance-pullrequest(master)#6468</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6468/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>headless-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2069740293">[master] ci:test:headless-functional - Hijky &gt; liferay-headless - PR#872 - 2022-11-21[22:42:38]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/15075/">publish-testray-report#15075</a><br/></div></div>

2022-11-22 08:23 UTC, Hijky commented
ci:test:headless-functional:nocompile

2022-11-22 08:23 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-11-22 08:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>headless-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/5469/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5469/jenkins-report.html">here</a>.</b></p>

2022-11-22 09:16 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:headless-functional - 11 out of 18 jobs passed in 51 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c1e7129f0993aa30e3f345ebd66fd58bc005e8e5">c1e7129f0993aa30e3f345ebd66fd58bc005e8e5</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c1e7129f0993aa30e3f345ebd66fd58bc005e8e5">c1e7129f0993aa30e3f345ebd66fd58bc005e8e5</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2068009625">EE Development Acceptance (master) - 4044 - 2022-11-21[05:09:24]</a></p><details><summary><strong>ci:test:headless-functional - 11 out of 18 jobs PASSED</strong></summary><div><h4>7 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/5469/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/263061/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350678/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/176267/"><strike>functional-tomcat90-mysql57-jdk8/0/2</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/327398/"><strike>functional-tomcat90-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/281887/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/337334/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/286137/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/263062/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350679/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/176268/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/286138/"><strike>functional-tomcat90-mysql57-jdk8/0/10</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/337335/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/116569/"><strike>functional-tomcat90-mysql57-jdk8/0/12</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/286140/"><strike>functional-tomcat90-mysql57-jdk8/0/13</strike></a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/119221/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/176270/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/327397/">functional-tomcat90-mysql57-jdk8/0/16</a></li></ul></li></ul></div><details><summary><strong>11 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5469/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at c1e7129f0993aa30e3f345ebd66fd58bc005e8e5:</strong></summary><ol><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350678//consoleText">functional-tomcat90-mysql57-jdk8/0/1</a><ol><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350678//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_HeadlessDeliveryBatchMode_CanCreateBlogPostingWithBatchPostCreateStrategyUpsert_">LocalFile.HeadlessDeliveryBatchMode#CanCreateBlogPostingWithBatchPostCreateStrategyUpsert</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-25/test-portal-acceptance-pullrequest(master)/5469/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.HeadlessDeliveryBatchMode_CanCreateBlogPostingWithBatchPostCreateStrategyUpsert/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-25/test-portal-acceptance-pullrequest(master)/5469/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.HeadlessDeliveryBatchMode_CanCreateBlogPostingWithBatchPostCreateStrategyUpsert/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-25/test-portal-acceptance-pullrequest(master)/5469/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/2066002662/history">Failed 4 of last 21</a></div></li><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350678//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_HeadlessDeliveryBatchMode_CanUpdateBlogPostingWithBatchPostCreateStrategyUpsertWhenOneOfThemAlreadyExisting_">LocalFile.HeadlessDeliveryBatchMode#CanUpdateBlogPostingWithBatchPostCreateStrategyUpsertWhenOneOfThemAlreadyExisting</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-25/test-portal-acceptance-pullrequest(master)/5469/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.HeadlessDeliveryBatchMode_CanUpdateBlogPostingWithBatchPostCreateStrategyUpsertWhenOneOfThemAlreadyExisting/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-25/test-portal-acceptance-pullrequest(master)/5469/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.HeadlessDeliveryBatchMode_CanUpdateBlogPostingWithBatchPostCreateStrategyUpsertWhenOneOfThemAlreadyExisting/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-25/test-portal-acceptance-pullrequest(master)/5469/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/2066003953/history">Failed 4 of last 21</a></div></li><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350678//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_HeadlessDeliveryBatchMode_CannotCreateBlogPostingWithBatchPutPartialUpdate_">LocalFile.HeadlessDeliveryBatchMode#CannotCreateBlogPostingWithBatchPutPartialUpdate</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-25/test-portal-acceptance-pullrequest(master)/5469/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.HeadlessDeliveryBatchMode_CannotCreateBlogPostingWithBatchPutPartialUpdate/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-25/test-portal-acceptance-pullrequest(mas [...]

2022-11-22 09:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/5469/">test-portal-acceptance-pullrequest(master)#5469</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5469/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>headless-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2069898957">[master] ci:test:headless-functional - Hijky &gt; liferay-headless - PR#872 - 2022-11-22[00:25:24]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/13520/">publish-testray-report#13520</a><br/></div></div>

2022-11-23 06:01 UTC, Hijky commented
ci:test:sf

2022-11-23 06:01 UTC, Hijky commented
ci:test:relevant

2022-11-23 06:01 UTC, Hijky commented
ci:test:headless-functional:nocompile

2022-11-23 06:01 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-11-23 06:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/1844/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1844/jenkins-report.html">here</a>.</b></p>

2022-11-23 06:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>headless-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/3239/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3239/jenkins-report.html">here</a>.</b></p>

2022-11-23 06:04 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a09c51e3154d20038182b127c69416abc9cf7b17">a09c51e3154d20038182b127c69416abc9cf7b17</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hijky/liferay-portal/tree/master-LPS-153326">master-LPS-153326</a><br/>Branch GIT ID: <a href="https://github.com/Hijky/liferay-portal/commit/7914c5c7e2e13aafeecb7287bfafc915c0cb4d2c">7914c5c7e2e13aafeecb7287bfafc915c0cb4d2c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/3806/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/3806/jenkins-report.html">here</a>.</h5></details></html>

2022-11-23 06:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/1844/">test-portal-acceptance-pullrequest(master)#1844</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1844/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2072235834">[master] ci:test:relevant - Hijky &gt; liferay-headless - PR#872 - 2022-11-22[22:01:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/4149/">publish-testray-report#4149</a><br/></div></div>

2022-11-23 06:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/3806/">test-portal-source-format#3806</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/3806/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2072235959">[master] ci:test:sf - Hijky &gt; liferay-headless - PR#872 - 2022-11-22[22:01:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/14009/">publish-testray-report#14009</a><br/></div></div>

2022-11-23 06:48 UTC, yanan commented on portal-web/test/functional/com/liferay/portalweb/macros/headless/headlessadminuser/MakeARelationshipWithSystemObjectThroughAPI.testcase
> +			var objectDefinitionId2 = ObjectDefinitionAPI.createAndPublishObjectDefinition(
how many object definitions do we need? Two custom object defitions and one system User, right? I'm curious why we use Id2 and Id4 here

2022-11-23 06:52 UTC, yanan commented on portal-web/test/functional/com/liferay/portalweb/macros/headless/headlessadminuser/MakeARelationshipWithSystemObjectThroughAPI.testcase
> +				en_US_label = "UsersSecondFoundations",
How about UserSecondFoundations for oneToMany?

2022-11-23 06:52 UTC, yanan commented on portal-web/test/functional/com/liferay/portalweb/macros/headless/headlessadminuser/MakeARelationshipWithSystemObjectThroughAPI.testcase
> +				en_US_label = "UsersSecondFoundations",
I'm also thinkg we already have some object definitions created in ObjectDefinitionAPI, is we're not must use the names Foundation and SecondFoundation, how about updating to other names which existing in ObjectDefinitionAPI?

2022-11-23 07:36 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:headless-functional - 9 out of 18 jobs passed in 1 hour 33 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a09c51e3154d20038182b127c69416abc9cf7b17">a09c51e3154d20038182b127c69416abc9cf7b17</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a09c51e3154d20038182b127c69416abc9cf7b17">a09c51e3154d20038182b127c69416abc9cf7b17</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2071628331">EE Development Acceptance (master) - 4047 - 2022-11-22[14:29:56]</a></p><details><summary><strong>ci:test:headless-functional - 9 out of 18 jobs PASSED</strong></summary><div><h4>9 Failed Jobs:</h4><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/3239/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/300340/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/131009/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/119855/"><strike>functional-tomcat90-mysql57-jdk8/0/2</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/321385/"><strike>functional-tomcat90-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/101293/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/133895/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/313513/"><strike>functional-tomcat90-mysql57-jdk8/0/6</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/352622/"><strike>functional-tomcat90-mysql57-jdk8/0/7</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/300341/"><strike>functional-tomcat90-mysql57-jdk8/0/8</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/283432/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/118586/"><strike>functional-tomcat90-mysql57-jdk8/0/10</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/288359/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/313514/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/113560/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/339101/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/130710/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/126813/"><strike>functional-tomcat90-mysql57-jdk8/0/16</strike></a></li></ul></li></ul></div><details><summary><strong>9 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3239/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/126813//consoleText">functional-tomcat90-mysql57-jdk8/0/16</a><ol><li><div><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/126813//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany_">LocalFile.MakeARelationshipWithSystemObjectThroughAPI#CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-34/test-portal-acceptance-pullrequest(master)/3239/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-34/test-portal-acceptance-pullrequest(master)/3239/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-34/test-portal-acceptance-pullrequest(master)/3239/functional-tomcat90-mysql57-jdk8/0/16/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/126813//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntries_">LocalFile.MakeARelationshipWithSystemObjectThroughAPI#CanRelateCustomObjectEntriesToSystemObjectEntries</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-34/test-portal-acceptance-pullrequest(master)/3239/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntries/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-34/test-portal-acceptance-pullrequest(master)/3239/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntries/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-34/test-portal-acceptance-pullrequest(master)/3239/functional-tomcat90-mysql57-jdk8/0/16/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/126813//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeARelationshipWithSystemObjectThroughAPI_DeletedObjectEntriesDoNotAppearInManyToManyRelationshipDetails_">LocalFile.MakeARelationshipWithSystemObjectThroughAPI#DeletedObjectEntriesDoNotAppearInManyToManyRelationshipDetails</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-34/test-portal-acceptance-pullrequest(master)/3239/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_DeletedObjectEntriesDoNotAppearInManyToManyRelationshipDetails/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-34/test-portal-acceptance-pullrequest(master)/3239/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_DeletedObjectEntriesDoNotAppearInManyToManyRelationshipDetails/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-34 [...]

2022-11-23 07:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/3239/">test-portal-acceptance-pullrequest(master)#3239</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3239/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>headless-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2072362496">[master] ci:test:headless-functional - Hijky &gt; liferay-headless - PR#872 - 2022-11-22[22:03:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/7939/">publish-testray-report#7939</a><br/></div></div>

2022-11-24 02:08 UTC, Hijky commented
ci:test:relevant

2022-11-24 02:08 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-11-24 02:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/1381/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1381/jenkins-report.html">here</a>.</b></p>

2022-11-24 02:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>headless-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/5246/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5246/jenkins-report.html">here</a>.</b></p>

2022-11-24 02:15 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/1381/">test-portal-source-format#1381</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1381/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2074480012">[master] ci:test:sf - Hijky &gt; liferay-headless - PR#872 - 2022-11-23[18:08:18]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/5517/">publish-testray-report#5517</a><br/></div></div>

2022-11-24 02:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/5546/">test-portal-acceptance-pullrequest(master)#5546</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5546/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2074480063">[master] ci:test:relevant - Hijky &gt; liferay-headless - PR#872 - 2022-11-23[18:15:04]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/13652/">publish-testray-report#13652</a><br/></div></div>

2022-11-24 03:05 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:headless-functional - 8 out of 18 jobs passed in 51 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/4051">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1287401_5246</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1157b5755cbd4b541c9bc50bca7a2279f815dde4">1157b5755cbd4b541c9bc50bca7a2279f815dde4</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/deaaa94a3bfd1bb6a8645a1fba0619a1d47af709">deaaa94a3bfd1bb6a8645a1fba0619a1d47af709</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2074481566">EE Development Acceptance (master) - 4050 - 2022-11-23[12:38:26]</a></p><details><summary><strong>ci:test:headless-functional - 8 out of 18 jobs PASSED</strong></summary><div><h4>10 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/5246/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/315582/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/312162/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/312161/"><strike>functional-tomcat90-mysql57-jdk8/0/2</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/312164/"><strike>functional-tomcat90-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/315583/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/354333/"><strike>functional-tomcat90-mysql57-jdk8/0/5</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/312163/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/312165/"><strike>functional-tomcat90-mysql57-jdk8/0/7</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/315584/"><strike>functional-tomcat90-mysql57-jdk8/0/8</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/354334/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/354335/"><strike>functional-tomcat90-mysql57-jdk8/0/10</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/315585/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/312166/"><strike>functional-tomcat90-mysql57-jdk8/0/12</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/336389/"><strike>functional-tomcat90-mysql57-jdk8/0/13</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/354336/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/315586/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/312160/">functional-tomcat90-mysql57-jdk8/0/16</a></li></ul></li></ul></div><details><summary><strong>8 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5246/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at deaaa94a3bfd1bb6a8645a1fba0619a1d47af709:</strong></summary><ol><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/312162//consoleText">functional-tomcat90-mysql57-jdk8/0/1</a><ol><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/312162//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_HeadlessDeliveryBatchMode_CanCreateBlogPostingWithBatchPostCreateStrategyInsertWithOn_Error_Continue_">LocalFile.HeadlessDeliveryBatchMode#CanCreateBlogPostingWithBatchPostCreateStrategyInsertWithOn_Error_Continue</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-28/test-portal-acceptance-pullrequest(master)/5246/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.HeadlessDeliveryBatchMode_CanCreateBlogPostingWithBatchPostCreateStrategyInsertWithOn_Error_Continue/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-28/test-portal-acceptance-pullrequest(master)/5246/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.HeadlessDeliveryBatchMode_CanCreateBlogPostingWithBatchPostCreateStrategyInsertWithOn_Error_Continue/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-28/test-portal-acceptance-pullrequest(master)/5246/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/2071643720/history">Failed 8 of last 25</a></div></li><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/312162//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_HeadlessDeliveryBatchMode_CannotCreateTwoSameBlogPostingsWithBatchPostCreateStrategyInsertWhenOneOfThemAlreadyExisting_">LocalFile.HeadlessDeliveryBatchMode#CannotCreateTwoSameBlogPostingsWithBatchPostCreateStrategyInsertWhenOneOfThemAlreadyExisting</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-28/test-portal-acceptance-pullrequest(master)/5246/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.HeadlessDeliveryBatchMode_CannotCreateTwoSameBlogPostingsWithBatchPostCreateStrategyInsertWhenOneOfThemAlreadyExisting/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-28/test-portal-acceptance-pullrequest(master)/5246/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.HeadlessDeliveryBatchMode_CannotCreateTwoSameBlogPostingsWithBatchPostCreateStrategyInsertWhenOneOfThemAlreadyExisting/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-28/test-portal-acceptance-pullrequest(master)/5246/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/2071643704/history">Failed 8 of last 25</a></div></li><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/312162//testRepor [...]

2022-11-24 03:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/5246/">test-portal-acceptance-pullrequest(master)#5246</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5246/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>headless-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2074659174">[master] ci:test:headless-functional - Hijky &gt; liferay-headless - PR#872 - 2022-11-23[18:13:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/12661/">publish-testray-report#12661</a><br/></div></div>

2022-11-24 07:01 UTC, magjed4289 requested changes

2022-11-24 07:01 UTC, magjed4289 commented on portal-web/test/functional/com/liferay/portalweb/macros/headless/headlessadminuser/MakeARelationshipWithSystemObjectThroughAPI.testcase
> +		var userAccountId1 = JSONUtil.getWithJSONPath("${responseWithUserAccount}", "$.items[?(@.givenName=='usergn1')].id");
I wonder if we can make the userAccountId1 and userAccountId2 values static 🤔 @yanan @Hijky please take a look at `ObjectDefinitionAPI.setUpGlobalobjectDefinitionId();` that we use in the `portal-web/test/functional/com/liferay/portalweb/tests/enduser/headless/AdvancedObjectAPI/SupportManyToManyRelationships.testcase` and check please if we can apply it here as well :)

2022-11-24 09:35 UTC, Hijky commented
ci:test:relevant

2022-11-24 09:35 UTC, Hijky commented
ci:test:headless-functional:nocompile

2022-11-24 09:35 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-11-24 09:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/3686/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3686/jenkins-report.html">here</a>.</b></p>

2022-11-24 09:39 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/66c46bfc28d5491bfcd3e8bf89212426a710f46c">66c46bfc28d5491bfcd3e8bf89212426a710f46c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hijky/liferay-portal/tree/master-LPS-153326">master-LPS-153326</a><br/>Branch GIT ID: <a href="https://github.com/Hijky/liferay-portal/commit/0957215d14fb789768ff42566ca697b8b8382c54">0957215d14fb789768ff42566ca697b8b8382c54</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3686/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3686/jenkins-report.html">here</a>.</h5></details></html>

2022-11-24 09:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>headless-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/5249/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5249/jenkins-report.html">here</a>.</b></p>

2022-11-24 09:52 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/5944/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5944/jenkins-report.html">here</a>.</b></p>

2022-11-24 10:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/5944/">test-portal-acceptance-pullrequest(master)#5944</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5944/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2075355939">[master] ci:test:relevant - Hijky &gt; liferay-headless - PR#872 - 2022-11-24[01:52:23]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/14237/">publish-testray-report#14237</a><br/></div></div>

2022-11-24 11:06 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:headless-functional - 7 out of 18 jobs passed in 1 hour 16 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/66c46bfc28d5491bfcd3e8bf89212426a710f46c">66c46bfc28d5491bfcd3e8bf89212426a710f46c</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/66c46bfc28d5491bfcd3e8bf89212426a710f46c">66c46bfc28d5491bfcd3e8bf89212426a710f46c</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2075020623">EE Development Acceptance (master) - 4053 - 2022-11-23[20:14:45]</a></p><details><summary><strong>ci:test:headless-functional - 7 out of 18 jobs PASSED</strong></summary><div><h4>11 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/5249/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/331606/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/341416/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/331605/"><strike>functional-tomcat90-mysql57-jdk8/0/2</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/331607/"><strike>functional-tomcat90-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/312833/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/341417/"><strike>functional-tomcat90-mysql57-jdk8/0/5</strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/130977/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/331608/"><strike>functional-tomcat90-mysql57-jdk8/0/7</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/341418/"><strike>functional-tomcat90-mysql57-jdk8/0/8</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/312835/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/312836/"><strike>functional-tomcat90-mysql57-jdk8/0/10</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/341419/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/130978/"><strike>functional-tomcat90-mysql57-jdk8/0/12</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316143/"><strike>functional-tomcat90-mysql57-jdk8/0/13</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/331609/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/312837/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/331604/"><strike>functional-tomcat90-mysql57-jdk8/0/16</strike></a></li></ul></li></ul></div><details><summary><strong>7 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5249/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/331604//consoleText">functional-tomcat90-mysql57-jdk8/0/16</a><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/331604//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeARelationshipWithSystemObjectThroughAPI_CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany_">LocalFile.MakeARelationshipWithSystemObjectThroughAPI#CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-28/test-portal-acceptance-pullrequest(master)/5249/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-28/test-portal-acceptance-pullrequest(master)/5249/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-28/test-portal-acceptance-pullrequest(master)/5249/functional-tomcat90-mysql57-jdk8/0/16/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/331604//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeARelationshipWithSystemObjectThroughAPI_CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany_">LocalFile.MakeARelationshipWithSystemObjectThroughAPI#CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-28/test-portal-acceptance-pullrequest(master)/5249/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-28/test-portal-acceptance-pullrequest(master)/5249/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-28/test-portal-acceptance-pullrequest(master)/5249/functional-tomcat90-mysql57-jdk8/0/16/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/331604//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany_">LocalFile.MakeARelationshipWithSystemObjectThroughAPI#CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-28/test-portal-acceptance-pullrequest(master)/5249/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-28/test-portal-acceptance-pullrequest(master)/5249/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany/summary.html.gz">Poshi Summary</a> - <a href="https:/ [...]

2022-11-24 11:10 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/5249/">test-portal-acceptance-pullrequest(master)#5249</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5249/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>headless-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2075456751">[master] ci:test:headless-functional - Hijky &gt; liferay-headless - PR#872 - 2022-11-24[01:49:53]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/12666/">publish-testray-report#12666</a><br/></div></div>

2022-11-24 11:56 UTC, Hijky commented
ci:test:headless-functional:nocompile

2022-11-24 11:56 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-11-24 13:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>headless-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/5507/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5507/jenkins-report.html">here</a>.</b></p>

2022-11-24 14:41 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:headless-functional - 7 out of 18 jobs passed in 1 hour 25 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/66c46bfc28d5491bfcd3e8bf89212426a710f46c">66c46bfc28d5491bfcd3e8bf89212426a710f46c</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/66c46bfc28d5491bfcd3e8bf89212426a710f46c">66c46bfc28d5491bfcd3e8bf89212426a710f46c</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2075020623">EE Development Acceptance (master) - 4053 - 2022-11-23[20:14:45]</a></p><details><summary><strong>ci:test:headless-functional - 7 out of 18 jobs PASSED</strong></summary><div><h4>11 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/5507/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/179938/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/117180/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/302867/"><strike>functional-tomcat90-mysql57-jdk8/0/2</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/266901/"><strike>functional-tomcat90-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121832/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/125955/"><strike>functional-tomcat90-mysql57-jdk8/0/5</strike></a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/133141/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/131821/"><strike>functional-tomcat90-mysql57-jdk8/0/7</strike></a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/127642/"><strike>functional-tomcat90-mysql57-jdk8/0/8</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/355308/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/331825/"><strike>functional-tomcat90-mysql57-jdk8/0/10</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/313061/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/133877/"><strike>functional-tomcat90-mysql57-jdk8/0/12</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316353/"><strike>functional-tomcat90-mysql57-jdk8/0/13</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/331826/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121217/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/341626/"><strike>functional-tomcat90-mysql57-jdk8/0/16</strike></a></li></ul></li></ul></div><details><summary><strong>7 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5507/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/341626//consoleText">functional-tomcat90-mysql57-jdk8/0/16</a><ol><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/341626//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeARelationshipWithSystemObjectThroughAPI_CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany_">LocalFile.MakeARelationshipWithSystemObjectThroughAPI#CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-25/test-portal-acceptance-pullrequest(master)/5507/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-25/test-portal-acceptance-pullrequest(master)/5507/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-25/test-portal-acceptance-pullrequest(master)/5507/functional-tomcat90-mysql57-jdk8/0/16/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/341626//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany_">LocalFile.MakeARelationshipWithSystemObjectThroughAPI#CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-25/test-portal-acceptance-pullrequest(master)/5507/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-25/test-portal-acceptance-pullrequest(master)/5507/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-25/test-portal-acceptance-pullrequest(master)/5507/functional-tomcat90-mysql57-jdk8/0/16/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/341626//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntries_">LocalFile.MakeARelationshipWithSystemObjectThroughAPI#CanRelateCustomObjectEntriesToSystemObjectEntries</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-25/test-portal-acceptance-pullrequest(master)/5507/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntries/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-25/test-portal-acceptance-pullrequest(master)/5507/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeARelationshipWithSystemObjectThroughAPI_CanRelateCustomObjectEntriesToSystemObjectEntries/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/log [...]

2022-11-24 14:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/5507/">test-portal-acceptance-pullrequest(master)#5507</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5507/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>headless-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2075731697">[master] ci:test:headless-functional - Hijky &gt; liferay-headless - PR#872 - 2022-11-24[05:16:24]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/13599/">publish-testray-report#13599</a><br/></div></div>

2022-11-24 18:29 UTC, magjed4289 commented
ci:test:headless-functional:nocompile

2022-11-24 18:29 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-11-24 18:29 UTC, magjed4289 commented
ci:test:sf

2022-11-24 18:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>headless-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/1900/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1900/jenkins-report.html">here</a>.</b></p>

2022-11-24 18:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/3976/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/3976/jenkins-report.html">here</a>.</b></p>

2022-11-24 18:34 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/28fc6fc316abb78456c692fd04cca362a22c5f97">28fc6fc316abb78456c692fd04cca362a22c5f97</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hijky/liferay-portal/tree/master-LPS-153326">master-LPS-153326</a><br/>Branch GIT ID: <a href="https://github.com/Hijky/liferay-portal/commit/572b6d44045cffbc8e93fc4f773cca93a8d2e420">572b6d44045cffbc8e93fc4f773cca93a8d2e420</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/3976/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/3976/jenkins-report.html">here</a>.</h5></details></html>

2022-11-24 18:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/3976/">test-portal-source-format#3976</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/3976/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2076212002">[master] ci:test:sf - Hijky &gt; liferay-headless - PR#872 - 2022-11-24[10:29:56]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/14908/">publish-testray-report#14908</a><br/></div></div>

2022-11-24 18:57 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:headless-functional - 0 out of 18 jobs passed in 28 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6c2346bebc0185a07e3a7046d2ecdf367be6ef2a">6c2346bebc0185a07e3a7046d2ecdf367be6ef2a</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6c2346bebc0185a07e3a7046d2ecdf367be6ef2a">6c2346bebc0185a07e3a7046d2ecdf367be6ef2a</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2076040439">EE Development Acceptance (master) - 4054 - 2022-11-24[05:07:17]</a></p><details><summary><strong>ci:test:headless-functional - 0 out of 18 jobs PASSED</strong></summary><div><h4>18 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/1900/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/126110/"><strike>functional-tomcat90-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/127805/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/131202/"><strike>functional-tomcat90-mysql57-jdk8/0/2</strike></a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/134041/"><strike>functional-tomcat90-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/133280/"><strike>functional-tomcat90-mysql57-jdk8/0/4</strike></a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/131660/"><strike>functional-tomcat90-mysql57-jdk8/0/5</strike></a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/132666/"><strike>functional-tomcat90-mysql57-jdk8/0/6</strike></a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/126111/"><strike>functional-tomcat90-mysql57-jdk8/0/7</strike></a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/127806/"><strike>functional-tomcat90-mysql57-jdk8/0/8</strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/131203/"><strike>functional-tomcat90-mysql57-jdk8/0/9</strike></a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/114312/"><strike>functional-tomcat90-mysql57-jdk8/0/10</strike></a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/131868/"><strike>functional-tomcat90-mysql57-jdk8/0/11</strike></a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/113299/"><strike>functional-tomcat90-mysql57-jdk8/0/12</strike></a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/132665/"><strike>functional-tomcat90-mysql57-jdk8/0/13</strike></a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/133281/"><strike>functional-tomcat90-mysql57-jdk8/0/14</strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121978/"><strike>functional-tomcat90-mysql57-jdk8/0/15</strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/131201/"><strike>functional-tomcat90-mysql57-jdk8/0/16</strike></a></li></ul></li></ul></div></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1900/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/126110//consoleText">functional-tomcat90-mysql57-jdk8/0/0</a><pre>build-common-java.compile:
    [javac] Compiling 4 source files to /opt/dev/projects/github/liferay-portal/portal-impl/classes
    [javac] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/util/PropsValues.java:1513: error: cannot find symbol
    [javac]       PropsUtil.get(PropsKeys.NOTIFICATION_EMAIL_TEMPLATE_RESTRICTED));
    [javac]                              ^
    [javac]   symbol:   variable NOTIFICATION_EMAIL_TEMPLATE_RESTRICTED
    [javac]   location: interface PropsKeys
    [javac] 1 error
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:4924: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1625: Task [run-batch-test] failed after [0] attempts; giving up.
     [echo] Error messages:
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1774: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1185: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build.xml:660: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common-java.xml:52: Compile failed; see the compiler error output for details.</pre></div></li><li><div><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/127805//consoleText">functional-tomcat90-mysql57-jdk8/0/1</a><pre>build-common-java.compile:
    [javac] Compiling 10 source files to /opt/dev/projects/github/liferay-portal/portal-impl/classes
    [javac] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/util/PropsValues.java:1513: error: cannot find symbol
    [javac]       PropsUtil.get(PropsKeys.NOTIFICATION_EMAIL_TEMPLATE_RESTRICTED));
    [javac]                              ^
    [javac]   symbol:   variable NOTIFICATION_EMAIL_TEMPLATE_RESTRICTED
    [javac]   location: interface PropsKeys
    [javac] Note: /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/webserver/WebServerServlet.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:4924: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1625: Task [run-batch-test] failed after [0] attempts; giving up.
     [echo] Error messages:
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1774: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1185: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build.xml:660: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common-java.xml:52: Compile failed; see the compiler er [...]

2022-11-24 19:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/1900/">test-portal-acceptance-pullrequest(master)#1900</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1900/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>headless-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2076280098">[master] ci:test:headless-functional - Hijky &gt; liferay-headless - PR#872 - 2022-11-24[10:29:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/4263/">publish-testray-report#4263</a><br/></div></div>

2022-11-24 21:49 UTC, magjed4289 commented
ci:test:headless-functional:nocompile

2022-11-24 21:58 UTC, magjed4289 commented
ci:test:headless-functional:nocompile

2022-11-24 21:58 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-11-24 21:58 UTC, magjed4289 commented
ci:test:sf

2022-11-24 21:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>headless-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/7094/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7094/jenkins-report.html">here</a>.</b></p>

2022-11-24 22:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/3852/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/3852/jenkins-report.html">here</a>.</b></p>

2022-11-24 22:02 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d46d88a52fc76f1adad0fa13cc21f07ab01fa3cf">d46d88a52fc76f1adad0fa13cc21f07ab01fa3cf</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hijky/liferay-portal/tree/master-LPS-153326">master-LPS-153326</a><br/>Branch GIT ID: <a href="https://github.com/Hijky/liferay-portal/commit/2dee72731770db2199ebf0ac155f2c343dede2dc">2dee72731770db2199ebf0ac155f2c343dede2dc</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/3852/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/3852/jenkins-report.html">here</a>.</h5></details></html>

2022-11-24 22:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/3852/">test-portal-source-format#3852</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/3852/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2076567537">[master] ci:test:sf - Hijky &gt; liferay-headless - PR#872 - 2022-11-24[13:59:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/14265/">publish-testray-report#14265</a><br/></div></div>

2022-11-24 22:37 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:headless-functional - 12 out of 18 jobs passed in 38 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/4056">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1327401_7094</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bf6952367c145188512c3924c6195ff5e233582b">bf6952367c145188512c3924c6195ff5e233582b</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/28fc6fc316abb78456c692fd04cca362a22c5f97">28fc6fc316abb78456c692fd04cca362a22c5f97</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2076562968">EE Development Acceptance (master) - 4055 - 2022-11-24[10:09:20]</a></p><details><summary><strong>ci:test:headless-functional - 12 out of 18 jobs PASSED</strong></summary><div><h4>6 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/7094/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121833/"><strike>functional-tomcat90-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332364/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121832/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121834/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/324561/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/303388/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332365/"><strike>functional-tomcat90-mysql57-jdk8/0/6</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/324562/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/303389/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332366/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/337899/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121835/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332367/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/291214/"><strike>functional-tomcat90-mysql57-jdk8/0/13</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/355907/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/303390/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332363/"><strike>functional-tomcat90-mysql57-jdk8/0/16</strike></a></li></ul></li></ul></div><details><summary><strong>12 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7094/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/291214//consoleText">functional-tomcat90-mysql57-jdk8/0/13</a><ol><li><div><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/291214//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ExposeInformationInNavigationMenus_GetAssetLibraryStructuredContentInformationInNavigationMenuWithSiteId_">LocalFile.ExposeInformationInNavigationMenus#GetAssetLibraryStructuredContentInformationInNavigationMenuWithSiteId</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-32/test-portal-acceptance-pullrequest(master)/7094/functional-tomcat90-mysql57-jdk8/0/13/LocalFile.ExposeInformationInNavigationMenus_GetAssetLibraryStructuredContentInformationInNavigationMenuWithSiteId/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-32/test-portal-acceptance-pullrequest(master)/7094/functional-tomcat90-mysql57-jdk8/0/13/LocalFile.ExposeInformationInNavigationMenus_GetAssetLibraryStructuredContentInformationInNavigationMenuWithSiteId/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-32/test-portal-acceptance-pullrequest(master)/7094/functional-tomcat90-mysql57-jdk8/0/13/jenkins-console.txt.gz">Console Output</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/2075026135/history">Failed 0 of last 25</a></div></li></ol></div></li><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332363//consoleText">functional-tomcat90-mysql57-jdk8/0/16</a><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332363//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeRelationshipWithSystemObject_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany_">LocalFile.MakeRelationshipWithSystemObject#CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-32/test-portal-acceptance-pullrequest(master)/7094/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-32/test-portal-acceptance-pullrequest(master)/7094/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-32/test-portal-acceptance-pullrequest(master)/7094/functional-tomcat90-mysql57-jdk8/0/16/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332363//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeRelationshipWithSystemObject_DeletedObjectEntriesDoNotAppearInManyToManyRelationshipDetails_">LocalFile.MakeRelationshipWithSystemObject#DeletedObjectEntriesDoNotAppearInManyToManyRelationshipDetails</a> - <a href="https://testray.liferay.com/reports [...]

2022-11-24 22:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/7094/">test-portal-acceptance-pullrequest(master)#7094</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7094/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>headless-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2076634537">[master] ci:test:headless-functional - Hijky &gt; liferay-headless - PR#872 - 2022-11-24[13:58:36]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/17859/">publish-testray-report#17859</a><br/></div></div>

2022-11-24 22:41 UTC, magjed4289 commented
@Hijky two of the new tests seem to fail, can you take a look?

2022-11-25 02:20 UTC, Hijky commented
ci:test:sf

2022-11-25 02:20 UTC, Hijky commented
ci:test:relevant

2022-11-25 02:21 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-11-25 02:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>headless-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/6547/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6547/jenkins-report.html">here</a>.</b></p>

2022-11-25 02:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/4205/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/4205/jenkins-report.html">here</a>.</b></p>

2022-11-25 02:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/caacd79e37ac59a8262b26e02633aa6e2f465d2d">caacd79e37ac59a8262b26e02633aa6e2f465d2d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hijky/liferay-portal/tree/master-LPS-153326">master-LPS-153326</a><br/>Branch GIT ID: <a href="https://github.com/Hijky/liferay-portal/commit/8916b21176f8f549ea0d10103a06ccf4a212d368">8916b21176f8f549ea0d10103a06ccf4a212d368</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/4205/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/4205/jenkins-report.html">here</a>.</h5></details></html>

2022-11-25 02:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/4205/">test-portal-source-format#4205</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/4205/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2077059559">[master] ci:test:sf - Hijky &gt; liferay-headless - PR#872 - 2022-11-24[18:22:18]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/15458/">publish-testray-report#15458</a><br/></div></div>

2022-11-25 02:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/1903/">test-portal-acceptance-pullrequest(master)#1903</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1903/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2077059550">[master] ci:test:relevant - Hijky &gt; liferay-headless - PR#872 - 2022-11-24[18:21:05]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/4275/">publish-testray-report#4275</a><br/></div></div>

2022-11-25 02:55 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:headless-functional - 13 out of 18 jobs passed in 34 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/69823205ae3ba77d6a20db26f450fa97426774ad">69823205ae3ba77d6a20db26f450fa97426774ad</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/69823205ae3ba77d6a20db26f450fa97426774ad">69823205ae3ba77d6a20db26f450fa97426774ad</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2076976192">EE Development Acceptance (master) - 4057 - 2022-11-24[15:05:39]</a></p><details><summary><strong>ci:test:headless-functional - 13 out of 18 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/6547/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/342102/"><strike>functional-tomcat90-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121944/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/355993/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/342103/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/324641/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121945/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/355994/"><strike>functional-tomcat90-mysql57-jdk8/0/6</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/303461/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121946/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/355995/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316687/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/313740/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/324642/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/342104/"><strike>functional-tomcat90-mysql57-jdk8/0/13</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/355996/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121947/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121943/">functional-tomcat90-mysql57-jdk8/0/16</a></li></ul></li></ul></div><details><summary><strong>13 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6547/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at 69823205ae3ba77d6a20db26f450fa97426774ad:</strong></summary><ol><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/342102//consoleText">functional-tomcat90-mysql57-jdk8/0/0</a><ol><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/342102//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_HeadlessDeliveryBatchMode_CanUpdateOneFieldOfBlogPostingWithBatchPutPartialUpdate_">LocalFile.HeadlessDeliveryBatchMode#CanUpdateOneFieldOfBlogPostingWithBatchPutPartialUpdate</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6547/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.HeadlessDeliveryBatchMode_CanUpdateOneFieldOfBlogPostingWithBatchPutPartialUpdate/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6547/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.HeadlessDeliveryBatchMode_CanUpdateOneFieldOfBlogPostingWithBatchPutPartialUpdate/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6547/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/2075032152/history">Failed 0 of last 25</a></div></li></ol></div></li><li><div><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121944//consoleText">functional-tomcat90-mysql57-jdk8/0/1</a><ol><li><div><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121944//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ExposeErcFromAssetLibraryForComments_CannotCreateTwoCommentsWithSameCustomExternalReferenceCode_">LocalFile.ExposeErcFromAssetLibraryForComments#CannotCreateTwoCommentsWithSameCustomExternalReferenceCode</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6547/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.ExposeErcFromAssetLibraryForComments_CannotCreateTwoCommentsWithSameCustomExternalReferenceCode/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6547/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.ExposeErcFromAssetLibraryForComments_CannotCreateTwoCommentsWithSameCustomExternalReferenceCode/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6547/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/2075031772/history">Failed 6 of last 25</a></div></li></ol></div></li><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/355994//consoleText">functional-tomcat90-mysql57-jdk8/0/6</a><ol><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/355994//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ExposeErcForCategories_CanRecieveErrorMessageByNotExistErcInCategory_">LocalFile.ExposeErcForCategories#CanRecieveErrorMessageByNotExistErcInCategory</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullreque [...]

2022-11-25 02:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/6547/">test-portal-acceptance-pullrequest(master)#6547</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6547/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>headless-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2077064009">[master] ci:test:headless-functional - Hijky &gt; liferay-headless - PR#872 - 2022-11-24[18:21:26]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/15246/">publish-testray-report#15246</a><br/></div></div>

2022-11-25 03:13 UTC, yanan commented on modules/apps/object/object-rest-test/src/testFunctional/macros/MakeARelationshipWithSystemObjectThroughAPI.testcase
> +@component-name = "portal-headless"
We need to move this file to tests folder.

2022-11-25 04:32 UTC, Hijky commented
ci:test:sf

2022-11-25 04:32 UTC, Hijky commented
ci:test:relevant

2022-11-25 04:32 UTC, Hijky commented
ci:test:headless-functional:nocompile

2022-11-25 04:32 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-11-25 04:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/7096/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7096/jenkins-report.html">here</a>.</b></p>

2022-11-25 04:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>headless-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/6077/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6077/jenkins-report.html">here</a>.</b></p>

2022-11-25 04:34 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/3959/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3959/jenkins-report.html">here</a>.</b></p>

2022-11-25 04:36 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/caacd79e37ac59a8262b26e02633aa6e2f465d2d">caacd79e37ac59a8262b26e02633aa6e2f465d2d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hijky/liferay-portal/tree/master-LPS-153326">master-LPS-153326</a><br/>Branch GIT ID: <a href="https://github.com/Hijky/liferay-portal/commit/68f63b7af7bb839646458fad9e60d35ea76a2cbf">68f63b7af7bb839646458fad9e60d35ea76a2cbf</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/3959/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3959/jenkins-report.html">here</a>.</h5></details></html>

2022-11-25 04:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/7096/">test-portal-acceptance-pullrequest(master)#7096</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7096/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2077100417">[master] ci:test:relevant - Hijky &gt; liferay-headless - PR#872 - 2022-11-24[20:32:58]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/17867/">publish-testray-report#17867</a><br/></div></div>

2022-11-25 04:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/3959/">test-portal-source-format#3959</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3959/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2077100645">[master] ci:test:sf - Hijky &gt; liferay-headless - PR#872 - 2022-11-24[20:33:07]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/15247/">publish-testray-report#15247</a><br/></div></div>

2022-11-25 05:16 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:headless-functional - 12 out of 19 jobs passed in 43 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/4058">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1317401_6077</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/caacd79e37ac59a8262b26e02633aa6e2f465d2d">caacd79e37ac59a8262b26e02633aa6e2f465d2d</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/69823205ae3ba77d6a20db26f450fa97426774ad">69823205ae3ba77d6a20db26f450fa97426774ad</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2076976192">EE Development Acceptance (master) - 4057 - 2022-11-24[15:05:39]</a></p><details><summary><strong>ci:test:headless-functional - 12 out of 19 jobs PASSED</strong></summary><div><h4>7 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/6077/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/356026/"><strike>functional-tomcat90-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/342128/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/303489/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/313783/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/303490/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332476/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121992/"><strike>functional-tomcat90-mysql57-jdk8/0/6</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/338021/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/356027/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/342129/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121993/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332477/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316934/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/303491/"><strike>functional-tomcat90-mysql57-jdk8/0/13</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/313784/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/342130/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121991/"><strike>functional-tomcat90-mysql57-jdk8/0/16</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332475/"><strike>functional-tomcat90-mysql57-jdk8/0/17</strike></a></li></ul></li></ul></div><details><summary><strong>12 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6077/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121991//consoleText">functional-tomcat90-mysql57-jdk8/0/16</a><ol><li><div><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121991//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany_">LocalFile.MakeRelationshipWithSystemObject#CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-31/test-portal-acceptance-pullrequest(master)/6077/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-31/test-portal-acceptance-pullrequest(master)/6077/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-31/test-portal-acceptance-pullrequest(master)/6077/functional-tomcat90-mysql57-jdk8/0/16/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121991//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany_">LocalFile.MakeRelationshipWithSystemObject#CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-31/test-portal-acceptance-pullrequest(master)/6077/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-31/test-portal-acceptance-pullrequest(master)/6077/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-31/test-portal-acceptance-pullrequest(master)/6077/functional-tomcat90-mysql57-jdk8/0/16/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121991//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeRelationshipWithSystemObject_DeletedObjectEntriesDoNotAppearInManyToManyRelationshipDetails_">LocalFile.MakeRelationshipWithSystemObject#DeletedObjectEntriesDoNotAppearInManyToManyRelationshipDetails</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-31/test-portal-acceptance-pullrequest(master)/6077/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_DeletedObjectEntriesDo [...]

2022-11-25 05:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/6077/">test-portal-acceptance-pullrequest(master)#6077</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6077/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>headless-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2077101985">[master] ci:test:headless-functional - Hijky &gt; liferay-headless - PR#872 - 2022-11-24[20:33:07]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/15460/">publish-testray-report#15460</a><br/></div></div>

2022-11-25 06:33 UTC, Hijky commented
ci:test:sf

2022-11-25 06:33 UTC, Hijky commented
ci:test:relevant

2022-11-25 06:33 UTC, Hijky commented
ci:test:headless-functional:nocompile

2022-11-25 06:33 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-11-25 06:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/3960/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3960/jenkins-report.html">here</a>.</b></p>

2022-11-25 06:36 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/caacd79e37ac59a8262b26e02633aa6e2f465d2d">caacd79e37ac59a8262b26e02633aa6e2f465d2d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hijky/liferay-portal/tree/master-LPS-153326">master-LPS-153326</a><br/>Branch GIT ID: <a href="https://github.com/Hijky/liferay-portal/commit/61217563d60b850e5d9e7c97d3238f6777ade04e">61217563d60b850e5d9e7c97d3238f6777ade04e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/3960/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3960/jenkins-report.html">here</a>.</h5></details></html>

2022-11-25 06:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/3960/">test-portal-source-format#3960</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3960/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2077105319">[master] ci:test:sf - Hijky &gt; liferay-headless - PR#872 - 2022-11-24[22:33:38]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/15249/">publish-testray-report#15249</a><br/></div></div>

2022-11-25 07:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>headless-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/4992/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4992/jenkins-report.html">here</a>.</b></p>

2022-11-25 07:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/6079/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6079/jenkins-report.html">here</a>.</b></p>

2022-11-25 07:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/6079/">test-portal-acceptance-pullrequest(master)#6079</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6079/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2077119314">[master] ci:test:relevant - Hijky &gt; liferay-headless - PR#872 - 2022-11-24[23:06:07]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/15464/">publish-testray-report#15464</a><br/></div></div>

2022-11-25 08:03 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:headless-functional - 12 out of 18 jobs passed in 58 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/4058">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1387401_4992</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/caacd79e37ac59a8262b26e02633aa6e2f465d2d">caacd79e37ac59a8262b26e02633aa6e2f465d2d</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/69823205ae3ba77d6a20db26f450fa97426774ad">69823205ae3ba77d6a20db26f450fa97426774ad</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2076976192">EE Development Acceptance (master) - 4057 - 2022-11-24[15:05:39]</a></p><details><summary><strong>ci:test:headless-functional - 12 out of 18 jobs PASSED</strong></summary><div><h4>6 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/4992/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316949/"><strike>functional-tomcat90-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122009/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122008/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316951/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122011/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316950/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122010/"><strike>functional-tomcat90-mysql57-jdk8/0/6</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122013/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316952/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122012/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316953/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122014/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122015/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316954/"><strike>functional-tomcat90-mysql57-jdk8/0/13</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/356047/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122016/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316948/"><strike>functional-tomcat90-mysql57-jdk8/0/16</strike></a></li></ul></li></ul></div><details><summary><strong>12 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4992/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316948//consoleText">functional-tomcat90-mysql57-jdk8/0/16</a><ol><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316948//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany_">LocalFile.MakeRelationshipWithSystemObject#CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/4992/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/4992/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/4992/functional-tomcat90-mysql57-jdk8/0/16/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316948//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany_">LocalFile.MakeRelationshipWithSystemObject#CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/4992/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/4992/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/4992/functional-tomcat90-mysql57-jdk8/0/16/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316948//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeRelationshipWithSystemObject_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany_">LocalFile.MakeRelationshipWithSystemObject#CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/4992/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance [...]

2022-11-25 08:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/4992/">test-portal-acceptance-pullrequest(master)#4992</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4992/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>headless-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2077123963">[master] ci:test:headless-functional - Hijky &gt; liferay-headless - PR#872 - 2022-11-24[23:05:16]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/11159/">publish-testray-report#11159</a><br/></div></div>

2022-11-25 11:40 UTC, magjed4289 commented
ci:test:headless-functional

2022-11-25 11:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>headless-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/5960/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5960/jenkins-report.html">here</a>.</b></p>

2022-11-25 13:10 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:headless-functional - 12 out of 18 jobs passed in 1 hour 29 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/caacd79e37ac59a8262b26e02633aa6e2f465d2d">caacd79e37ac59a8262b26e02633aa6e2f465d2d</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/caacd79e37ac59a8262b26e02633aa6e2f465d2d">caacd79e37ac59a8262b26e02633aa6e2f465d2d</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2077126032">EE Development Acceptance (master) - 4058 - 2022-11-24[20:14:01]</a></p><details><summary><strong>ci:test:headless-functional - 12 out of 18 jobs PASSED</strong></summary><div><h4>6 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/5960/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/356453/"><strike>functional-tomcat90-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122467/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/114431/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/120960/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122468/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121668/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/114432/"><strike>functional-tomcat90-mysql57-jdk8/0/6</strike></a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/117505/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/132822/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/356454/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/102599/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/134208/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121667/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/114430/"><strike>functional-tomcat90-mysql57-jdk8/0/13</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/267848/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122469/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121666/"><strike>functional-tomcat90-mysql57-jdk8/0/16</strike></a></li></ul></li></ul></div><details><summary><strong>12 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5960/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121666//consoleText">functional-tomcat90-mysql57-jdk8/0/16</a><ol><li><div><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121666//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany_">LocalFile.MakeRelationshipWithSystemObject#CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5960/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5960/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5960/functional-tomcat90-mysql57-jdk8/0/16/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121666//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany_">LocalFile.MakeRelationshipWithSystemObject#CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5960/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5960/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5960/functional-tomcat90-mysql57-jdk8/0/16/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121666//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeRelationshipWithSystemObject_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany_">LocalFile.MakeRelationshipWithSystemObject#CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5960/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5960/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5960/functional-tomcat90-mysql57-jdk8/0/16/jenkins-console.txt.gz">Console Output</a></div></li><li>...</li></ol></div></l [...]

2022-11-25 13:15 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/5960/">test-portal-acceptance-pullrequest(master)#5960</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5960/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>headless-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2077449148">[master] ci:test:headless-functional - Hijky &gt; liferay-headless - PR#872 - 2022-11-25[03:40:59]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/14277/">publish-testray-report#14277</a><br/></div></div>

2022-11-25 18:19 UTC, magjed4289 commented
ci:test:headless-functional:nocompile

2022-11-25 18:19 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-11-25 18:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>headless-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/3263/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3263/jenkins-report.html">here</a>.</b></p>

2022-11-25 18:26 UTC, magjed4289 commented
ci:stop

2022-11-25 18:26 UTC, magjed4289 commented
ci:test:headless-functional:nocompile

2022-11-25 18:26 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-11-25 18:27 UTC, magjed4289 commented
ci:test:sf

2022-11-25 18:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>headless-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/6568/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6568/jenkins-report.html">here</a>.</b></p>

2022-11-25 18:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/3241/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/3241/jenkins-report.html">here</a>.</b></p>

2022-11-25 18:34 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ec453722f5b8c22702409c8f5f3aba381edbd8a9">ec453722f5b8c22702409c8f5f3aba381edbd8a9</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hijky/liferay-portal/tree/master-LPS-153326">master-LPS-153326</a><br/>Branch GIT ID: <a href="https://github.com/Hijky/liferay-portal/commit/51a39e26895a9db7233c909648e4ec37dc2bb1f3">51a39e26895a9db7233c909648e4ec37dc2bb1f3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/3241/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/3241/jenkins-report.html">here</a>.</h5></details></html>

2022-11-25 18:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/3241/">test-portal-source-format#3241</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/3241/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2078250376">[master] ci:test:sf - Hijky &gt; liferay-headless - PR#872 - 2022-11-25[10:27:21]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/11181/">publish-testray-report#11181</a><br/></div></div>

2022-11-25 19:11 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:headless-functional - 12 out of 18 jobs passed in 51 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ec453722f5b8c22702409c8f5f3aba381edbd8a9">ec453722f5b8c22702409c8f5f3aba381edbd8a9</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ec453722f5b8c22702409c8f5f3aba381edbd8a9">ec453722f5b8c22702409c8f5f3aba381edbd8a9</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2078266237">EE Development Acceptance (master) - 4060 - 2022-11-25[07:36:08]</a></p><details><summary><strong>ci:test:headless-functional - 12 out of 18 jobs PASSED</strong></summary><div><h4>6 Failed Jobs:</h4><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/3263/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/113632/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/133003/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/343085/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/343086/"><strike>functional-tomcat90-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/325584/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/131559/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121131/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/131975/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122303/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/133005/"><strike>functional-tomcat90-mysql57-jdk8/0/9</strike></a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/102780/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/135165/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/113633/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/117694/"><strike>functional-tomcat90-mysql57-jdk8/0/13</strike></a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121133/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/131560/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/343084/"><strike>functional-tomcat90-mysql57-jdk8/0/16</strike></a></li></ul></li></ul></div><details><summary><strong>12 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3263/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/343084//consoleText">functional-tomcat90-mysql57-jdk8/0/16</a><ol><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/343084//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany_">LocalFile.MakeRelationshipWithSystemObject#CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-34/test-portal-acceptance-pullrequest(master)/3263/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-34/test-portal-acceptance-pullrequest(master)/3263/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-34/test-portal-acceptance-pullrequest(master)/3263/functional-tomcat90-mysql57-jdk8/0/16/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/343084//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany_">LocalFile.MakeRelationshipWithSystemObject#CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-34/test-portal-acceptance-pullrequest(master)/3263/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-34/test-portal-acceptance-pullrequest(master)/3263/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-34/test-portal-acceptance-pullrequest(master)/3263/functional-tomcat90-mysql57-jdk8/0/16/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/343084//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeRelationshipWithSystemObject_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany_">LocalFile.MakeRelationshipWithSystemObject#CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-34/test-portal-acceptance-pullrequest(master)/3263/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-34/test-portal-acceptance-pullrequest(master)/3263/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-34/test-portal-acceptance-pullrequest(master)/3263/functional-tomcat90-mysql57-jdk8/0/16/jenkins-console.txt.gz">Console Output</a></div></li><li>...</li></ol></div></ [...]

2022-11-25 19:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/3263/">test-portal-acceptance-pullrequest(master)#3263</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3263/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>headless-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2078343381">[master] ci:test:headless-functional - Hijky &gt; liferay-headless - PR#872 - 2022-11-25[10:19:58]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/7975/">publish-testray-report#7975</a><br/></div></div>

2022-11-25 19:17 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:headless-functional - 12 out of 18 jobs passed in 50 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ec453722f5b8c22702409c8f5f3aba381edbd8a9">ec453722f5b8c22702409c8f5f3aba381edbd8a9</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ec453722f5b8c22702409c8f5f3aba381edbd8a9">ec453722f5b8c22702409c8f5f3aba381edbd8a9</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2078266237">EE Development Acceptance (master) - 4060 - 2022-11-25[07:36:08]</a></p><details><summary><strong>ci:test:headless-functional - 12 out of 18 jobs PASSED</strong></summary><div><h4>6 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/6568/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/314670/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/357050/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/339056/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/339057/"><strike>functional-tomcat90-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/333405/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/325622/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/325621/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/286878/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/314671/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/357051/"><strike>functional-tomcat90-mysql57-jdk8/0/9</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/325623/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/333406/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/339058/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/291141/"><strike>functional-tomcat90-mysql57-jdk8/0/13</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/268363/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122949/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/339055/"><strike>functional-tomcat90-mysql57-jdk8/0/16</strike></a></li></ul></li></ul></div><details><summary><strong>12 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6568/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/339055//consoleText">functional-tomcat90-mysql57-jdk8/0/16</a><ol><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/339055//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany_">LocalFile.MakeRelationshipWithSystemObject#CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6568/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6568/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByManyToMany/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6568/functional-tomcat90-mysql57-jdk8/0/16/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/339055//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany_">LocalFile.MakeRelationshipWithSystemObject#CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6568/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6568/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelatedToSystemObjectByOneToMany/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6568/functional-tomcat90-mysql57-jdk8/0/16/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/339055//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeRelationshipWithSystemObject_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany_">LocalFile.MakeRelationshipWithSystemObject#CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6568/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6568/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.MakeRelationshipWithSystemObject_CanRelateCustomObjectEntriesToSystemObjectEntriesByManyToMany/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6568/functional-tomcat90-mysql57-jdk8/0/16/jenkins-console.txt.gz">Console Output</a></div></li><li>...</li></ol></d [...]

2022-11-25 19:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/6568/">test-portal-acceptance-pullrequest(master)#6568</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6568/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>headless-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2078354850">[master] ci:test:headless-functional - Hijky &gt; liferay-headless - PR#872 - 2022-11-25[10:26:54]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/15283/">publish-testray-report#15283</a><br/></div></div>

2022-11-28 06:06 UTC, Hijky commented
ci:test:sf

2022-11-28 06:06 UTC, Hijky commented
ci:test:relevant

2022-11-28 06:07 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-11-28 06:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/6589/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6589/jenkins-report.html">here</a>.</b></p>

2022-11-28 06:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>headless-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/6106/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6106/jenkins-report.html">here</a>.</b></p>

2022-11-28 06:09 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b5d0ff22da454ed670f0865f6ae1f966ff911141">b5d0ff22da454ed670f0865f6ae1f966ff911141</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hijky/liferay-portal/tree/master-LPS-153326">master-LPS-153326</a><br/>Branch GIT ID: <a href="https://github.com/Hijky/liferay-portal/commit/39b32fcd2a8ef39fc823ba9876717a4f46fa7d56">39b32fcd2a8ef39fc823ba9876717a4f46fa7d56</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/1322/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1322/jenkins-report.html">here</a>.</h5></details></html>

2022-11-28 06:12 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/1322/">test-portal-source-format#1322</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1322/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2081649595">[master] ci:test:sf - Hijky &gt; liferay-headless - PR#872 - 2022-11-27[22:07:02]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/4384/">publish-testray-report#4384</a><br/></div></div>

2022-11-28 06:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/6589/">test-portal-acceptance-pullrequest(master)#6589</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6589/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2081649630">[master] ci:test:relevant - Hijky &gt; liferay-headless - PR#872 - 2022-11-27[22:07:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/15340/">publish-testray-report#15340</a><br/></div></div>

2022-11-28 07:09 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:headless-functional - 17 out of 25 jobs passed in 1 hour 1 minute</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b5d0ff22da454ed670f0865f6ae1f966ff911141">b5d0ff22da454ed670f0865f6ae1f966ff911141</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b5d0ff22da454ed670f0865f6ae1f966ff911141">b5d0ff22da454ed670f0865f6ae1f966ff911141</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2080607524">EE Development Acceptance (master) - 4063 - 2022-11-27[05:05:25]</a></p><details><summary><strong>ci:test:headless-functional - 17 out of 25 jobs PASSED</strong></summary><div><h4>8 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/6106/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334425/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/305515/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358231/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334426/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/305516/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/124140/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358232/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/305517/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/124139/"><strike>functional-tomcat90-mysql57-jdk8/0/8</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358233/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358234/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/344185/"><strike>functional-tomcat90-mysql57-jdk8/0/11</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/305518/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358235/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/326713/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/315761/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358228/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358229/"><strike>functional-tomcat90-mysql57-jdk8/0/17</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358230/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/305514/"><strike>functional-tomcat90-mysql57-jdk8/0/19</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334427/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/315760/"><strike>functional-tomcat90-mysql57-jdk8/0/21</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/124141/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334428/"><strike>functional-tomcat90-mysql57-jdk8/0/23</strike></a></li></ul></li></ul></div><details><summary><strong>17 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6106/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/315760//consoleText">functional-tomcat90-mysql57-jdk8/0/21</a><ol><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/315760//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ImportExport_CanScheduleImport_">LocalFile.ImportExport#CanScheduleImport</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-31/test-portal-acceptance-pullrequest(master)/6106/functional-tomcat90-mysql57-jdk8/0/21/LocalFile.ImportExport_CanScheduleImport/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-31/test-portal-acceptance-pullrequest(master)/6106/functional-tomcat90-mysql57-jdk8/0/21/LocalFile.ImportExport_CanScheduleImport/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-31/test-portal-acceptance-pullrequest(master)/6106/functional-tomcat90-mysql57-jdk8/0/21/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334428//consoleText">functional-tomcat90-mysql57-jdk8/0/23</a><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334428//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelaatedToSystemObjectByManyToMany_">LocalFile.MakeRelationshipWithSystemObject#CanDeleteCustomObjectEntryRelaatedToSystemObjectByManyToMany</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-31/test-portal-acceptance-pullrequest(master)/6106/functional-tomcat90-mysql57-jdk8/0/23/LocalFile.MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelaatedToSystemObjectByManyToMany/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-31/test-portal-acceptance-pullrequest(master)/6106/functional-tomcat90-mysql57-jdk8/0/23/LocalFile.MakeRelationshipWithSystemObject_CanDeleteCustomObjectEntryRelaatedToSystemObjectByManyToMany/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-31/test-portal-acceptance-pullrequest(master)/6106/functional-tomcat90-mysql57-jdk8/0/23/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334428//testReport/com.liferay.poshi.runner/Poshi [...]

2022-11-28 07:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/6106/">test-portal-acceptance-pullrequest(master)#6106</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6106/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>headless-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2081720439">[master] ci:test:headless-functional - Hijky &gt; liferay-headless - PR#872 - 2022-11-27[22:07:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/15522/">publish-testray-report#15522</a><br/></div></div>

2022-11-28 10:13 UTC, magjed4289 commented
ci:test:headless-functional:nocompile

2022-11-28 10:13 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-11-28 10:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>headless-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/5004/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5004/jenkins-report.html">here</a>.</b></p>

2022-11-28 10:42 UTC, magjed4289 commented
ci:test:headless-functional:nocompile

2022-11-28 10:42 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-11-28 10:51 UTC, magjed4289 commented
ci:stop

2022-11-28 11:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>headless-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/5006/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5006/jenkins-report.html">here</a>.</b></p>

2022-11-28 12:13 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:headless-functional - 17 out of 25 jobs passed in 1 hour 59 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b5d0ff22da454ed670f0865f6ae1f966ff911141">b5d0ff22da454ed670f0865f6ae1f966ff911141</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b5d0ff22da454ed670f0865f6ae1f966ff911141">b5d0ff22da454ed670f0865f6ae1f966ff911141</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2080607524">EE Development Acceptance (master) - 4063 - 2022-11-27[05:05:25]</a></p><details><summary><strong>ci:test:headless-functional - 17 out of 25 jobs PASSED</strong></summary><div><h4>8 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/5004/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358614/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/292375/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/107998/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/340498/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334775/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334774/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/344530/"><strike>functional-tomcat90-mysql57-jdk8/0/6</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/269507/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/305865/"><strike>functional-tomcat90-mysql57-jdk8/0/8</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334776/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/269508/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/288052/"><strike>functional-tomcat90-mysql57-jdk8/0/11</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/182223/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/327075/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/132694/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358615/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334773/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/124520/"><strike>functional-tomcat90-mysql57-jdk8/0/17</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/124521/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/124522/"><strike>functional-tomcat90-mysql57-jdk8/0/19</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/318950/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316136/"><strike>functional-tomcat90-mysql57-jdk8/0/21</strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/135887/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/124523/">functional-tomcat90-mysql57-jdk8/0/23</a></li></ul></li></ul></div><details><summary><strong>17 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5004/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/344530//consoleText">functional-tomcat90-mysql57-jdk8/0/6</a><ol><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/344530//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ExposeInformationInNavigationMenus_GetAssetLibraryStructuredContentInformationInNavigationMenuWithSiteId_">LocalFile.ExposeInformationInNavigationMenus#GetAssetLibraryStructuredContentInformationInNavigationMenuWithSiteId</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/5004/functional-tomcat90-mysql57-jdk8/0/6/LocalFile.ExposeInformationInNavigationMenus_GetAssetLibraryStructuredContentInformationInNavigationMenuWithSiteId/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/5004/functional-tomcat90-mysql57-jdk8/0/6/LocalFile.ExposeInformationInNavigationMenus_GetAssetLibraryStructuredContentInformationInNavigationMenuWithSiteId/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/5004/functional-tomcat90-mysql57-jdk8/0/6/jenkins-console.txt.gz">Console Output</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/2080047088/history">Failed 0 of last 25</a></div></li></ol></div></li><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316136//consoleText">functional-tomcat90-mysql57-jdk8/0/21</a><ol><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316136//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ImportExport_CanScheduleImport_">LocalFile.ImportExport#CanScheduleImport</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/5004/functional-tomcat90-mysql57-jdk8/0/21/LocalFile.ImportExport_CanScheduleImport/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/5004/functional-tomcat90-mysql57-jdk8/0/21/LocalFile.ImportExport_CanScheduleImport/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/5004/functional-tomcat90-mysql57-jdk8/0/21/jenkins-console.txt.gz">Console Output</a></div></li></ol [...]

2022-11-28 12:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/5004/">test-portal-acceptance-pullrequest(master)#5004</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5004/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>headless-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2082165257">[master] ci:test:headless-functional - Hijky &gt; liferay-headless - PR#872 - 2022-11-28[02:13:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/11206/">publish-testray-report#11206</a><br/></div></div>

2022-11-28 13:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/5006/">test-portal-acceptance-pullrequest(master)#5006</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5006/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>headless-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2082183232">[master] ci:test:headless-functional - Hijky &gt; liferay-headless - PR#872 - 2022-11-28[03:37:03]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/11211/">publish-testray-report#11211</a><br/></div></div>

2022-11-28 15:00 UTC, magjed4289 commented
liferay/ci:test:headless-functional:nocompile

2022-11-28 15:01 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-11-28 15:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>headless-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/6605/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6605/jenkins-report.html">here</a>.</b></p>

2022-11-28 16:05 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:headless-functional - 18 out of 25 jobs passed in 55 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/4064">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1377401_6605</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e56aff76be7cb4dbdebbb3eb2730fb199918ac2c">e56aff76be7cb4dbdebbb3eb2730fb199918ac2c</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b5d0ff22da454ed670f0865f6ae1f966ff911141">b5d0ff22da454ed670f0865f6ae1f966ff911141</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2080607524">EE Development Acceptance (master) - 4063 - 2022-11-27[05:05:25]</a></p><details><summary><strong>ci:test:headless-functional - 18 out of 25 jobs PASSED</strong></summary><div><h4>7 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/6605/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/340916/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/335174/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316536/"><strike>functional-tomcat90-mysql57-jdk8/0/2</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/340917/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316537/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/319338/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/269887/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/319339/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/359075/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/335175/"><strike>functional-tomcat90-mysql57-jdk8/0/9</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316538/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/335176/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/124965/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/269889/"><strike>functional-tomcat90-mysql57-jdk8/0/13</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316539/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/103343/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/319336/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/335173/"><strike>functional-tomcat90-mysql57-jdk8/0/17</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/340915/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/319337/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/269888/"><strike>functional-tomcat90-mysql57-jdk8/0/20</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/340918/"><strike>functional-tomcat90-mysql57-jdk8/0/21</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/359076/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/319340/">functional-tomcat90-mysql57-jdk8/0/23</a></li></ul></li></ul></div><details><summary><strong>18 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6605/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/340918//consoleText">functional-tomcat90-mysql57-jdk8/0/21</a><ol><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/340918//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ImportExport_CanScheduleImport_">LocalFile.ImportExport#CanScheduleImport</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6605/functional-tomcat90-mysql57-jdk8/0/21/LocalFile.ImportExport_CanScheduleImport/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6605/functional-tomcat90-mysql57-jdk8/0/21/LocalFile.ImportExport_CanScheduleImport/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6605/functional-tomcat90-mysql57-jdk8/0/21/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol><hr/><details><summary><strong>Failures in common with <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at b5d0ff22da454ed670f0865f6ae1f966ff911141:</strong></summary><ol><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316536//consoleText">functional-tomcat90-mysql57-jdk8/0/2</a><ol><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316536//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ExposeErcFromAssetLibraryForComments_CannotCreateTwoCommentsWithSameCustomExternalReferenceCode_">LocalFile.ExposeErcFromAssetLibraryForComments#CannotCreateTwoCommentsWithSameCustomExternalReferenceCode</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6605/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.ExposeErcFromAssetLibraryForComments_CannotCreateTwoCommentsWithSameCustomExternalReferenceCode/index.html.gz">Poshi Report</a> - <a href [...]

2022-11-28 17:07 UTC, magjed4289 commented
ci:test:sf

2022-11-28 17:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/3708/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3708/jenkins-report.html">here</a>.</b></p>

2022-11-28 17:11 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/19a3ff2484b18a9f71ec25657ccaac1a590e0144">19a3ff2484b18a9f71ec25657ccaac1a590e0144</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hijky/liferay-portal/tree/master-LPS-153326">master-LPS-153326</a><br/>Branch GIT ID: <a href="https://github.com/Hijky/liferay-portal/commit/39b32fcd2a8ef39fc823ba9876717a4f46fa7d56">39b32fcd2a8ef39fc823ba9876717a4f46fa7d56</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3708/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3708/jenkins-report.html">here</a>.</h5></details></html>

2022-11-28 17:12 UTC, magjed4289 commented
ci:forward

2022-11-28 17:12 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2022-11-28 17:13 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-37.liferay.com/job/forward-pullrequest/634//consoleFull)

2022-11-28 17:13 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/126950
[Console](https://test-1-37.liferay.com/job/forward-pullrequest/634//consoleFull)

2022-11-28 17:13 UTC, closed without merging

2022-11-28 17:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3708/">test-portal-source-format#3708</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3708/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-headless/liferay-portal/pull/872">liferay-headless#872</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2082913742">[master] ci:test:sf - Hijky &gt; liferay-headless - PR#872 - 2022-11-28[09:07:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/13676/">publish-testray-report#13676</a><br/></div></div>